<?php

namespace Modules\Finance\Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Modules\CRM\Models\Customer;
use Modules\CRM\Models\Lead;
use Modules\CRM\Models\Proposal;
use Modules\CRM\Models\SalesPlan;
use Modules\Finance\Enums\ProfitabilityAnalysisStatus;
use Modules\Finance\Models\AccrueRevenue;
use Modules\Finance\Models\ProfitabilityAnalysis;
use Modules\MasterData\Models\ProductCluster;
use Modules\MasterData\Models\ProjectArea;
use Modules\MasterData\Models\ProjectType;
use Modules\MasterData\Models\Tax;
use Modules\MasterData\Models\WorkScheme;
use Tests\TestCase;

class AccrualGenerationTest extends TestCase
{
    use RefreshDatabase, WithFaker;

    public function test_automated_12_month_accrual_generation_on_pa_approval(): void
    {
        // 1. Setup required master data
        $customer = Customer::factory()->create(['code' => 'CUS']);
        $projectArea = ProjectArea::factory()->create(['code' => 'ARE']);
        $productCluster = ProductCluster::factory()->create(['code' => 'CLS']);
        $tax = Tax::factory()->create(['code' => 'TX']);
        $workScheme = WorkScheme::factory()->create();
        $projectType = ProjectType::factory()->create(['code' => 'TYP']);

        // 2. Setup Lead and Sales Plan with 12 months breakdown
        // Use 'lead' status to prevent LeadObserver from auto-creating a SalesPlan
        $lead = Lead::factory()->create([
            'customer_id' => $customer->id,
            'project_area_id' => $projectArea->id,
            'product_cluster_id' => $productCluster->id,
            'tax_id' => $tax->id,
            'project_type_id' => $projectType->id,
            'status' => \Modules\CRM\Enums\LeadStatus::Lead,
        ]);

        // Move to Approach to trigger SalesPlan creation via Observer, or create it manually
        // Here we create it manually to control the ID and dates exactly as needed
        $salesPlan = SalesPlan::factory()->create([
            'lead_id' => $lead->id,
            'start_date' => '2026-01-01',
            'end_date' => '2026-12-31',
        ]);

        Proposal::factory()->create([
            'lead_id' => $lead->id,
            'status' => 'draft',
        ]);

        // Manually create 12 months breakdown to match the budget requirement
        for ($i = 1; $i <= 12; $i++) {
            $salesPlan->monthlyBreakdowns()->create([
                'year' => 2026,
                'month' => $i,
                'budget_amount' => 10000000 * $i, // Gradual increase for testing
            ]);
        }

        // 3. Create PA and ensure monthly records are generated (this usually happens via Observer)
        /** @var ProfitabilityAnalysis $pa */
        $pa = ProfitabilityAnalysis::factory()->create([
            'lead_id' => $lead->id,
            'customer_id' => $customer->id,
            'project_area_id' => $projectArea->id,
            'product_cluster_id' => $productCluster->id,
            'tax_id' => $tax->id,
            'project_type_id' => $projectType->id,
            'work_scheme_id' => $workScheme->id,
            'status' => ProfitabilityAnalysisStatus::Draft,
            'start_date' => '2026-01-01',
            'end_date' => '2026-12-31',
            'revenue_per_month' => 10000000,
        ]);

        // Check if monthlies are there (generated by ProfitabilityAnalysisObserver::generateMonthlyRecords)
        $this->assertEquals(12, $pa->monthlies()->count());

        // 4. Approve PA to trigger Project creation and Accrual generation
        $pa->update(['status' => ProfitabilityAnalysisStatus::Approved]);

        // 5. Assertions
        // Check Project was created
        $this->assertDatabaseHas('projects', [
            'profitability_analysis_id' => $pa->id,
        ]);

        // Check 12 AccrueRevenue records were created
        $this->assertEquals(12, AccrueRevenue::where('project_id', $pa->project->id)->count());

        // Check values match Sales Plan budget (e.g. Month 5 should be 50,000,000)
        $accrualMonth5 = AccrueRevenue::where('project_id', $pa->project->id)
            ->where('month', 5)
            ->first();

        $this->assertNotNull($accrualMonth5);
        $this->assertEquals(50000000.00, (float) $accrualMonth5->total_amount_estimated);
        $this->assertEquals(0.00, (float) $accrualMonth5->total_amount_actual);

        // Check items
        $this->assertEquals(1, $accrualMonth5->items()->count());
        $this->assertEquals(50000000.00, (float) $accrualMonth5->items()->first()->amount_estimated);
    }
}
