<?php

namespace Modules\Project\Filament\Clusters\Project\Resources\Projects\Resources\WorkCompletionReports\Schemas;

use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\MorphToSelect;
use Filament\Forms\Components\Repeater;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\SpatieMediaLibraryFileUpload;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Components\Grid;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Components\Utilities\Set;
use Filament\Schemas\Schema;
use Modules\CRM\Enums\SalesOrderType;
use Modules\CRM\Models\CooperationAgreement;
use Modules\CRM\Models\Customer;
use Modules\CRM\Models\MinutesOfAgreement;
use Modules\CRM\Models\PurchaseOrder;
use Modules\CRM\Models\SalesOrder;
use Modules\CRM\Models\WorkOrder;
use Modules\MasterData\Enums\Gender;
use Modules\Project\Enums\WorkCompletionStatus;
use Modules\Project\Models\Project;
use Modules\Project\Models\WorkCompletionReport;

class WorkCompletionReportForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make('Documents')
                    ->description('Download the draft report for signing, and upload the final scanned version to complete the workflow.')
                    ->schema([
                        Grid::make(2)
                            ->schema([
                                SpatieMediaLibraryFileUpload::make('draft_report')
                                    ->label('Draft BAPP (Unsigned)')
                                    ->collection('draft_report')
                                    ->disk('s3')
                                    ->downloadable()
                                    ->openable()
                                    ->placeholder('System-generated draft')
                                    ->helperText('This document is automatically generated by the system for signing purposes.'),

                                SpatieMediaLibraryFileUpload::make('signed_report')
                                    ->label('Signed BAPP (Final Scan)')
                                    ->collection('signed_report')
                                    ->disk('s3')
                                    ->downloadable()
                                    ->openable()
                                    ->placeholder('Upload scanned signature')
                                    ->helperText('Upload the final scanned document that has been signed by all relevant parties.')
                                    ->required(fn (Get $get) => $get('status') === WorkCompletionStatus::Submitted->value &&
                                        $get('so_type') !== \Modules\CRM\Enums\SalesOrderType::Internal->value
                                    ),
                            ]),
                    ])->columnSpanFull()
                    ->collapsible(),

                Section::make('Report Details')
                    ->description('Specify the basic information for this Work Completion Report.')
                    ->schema([
                        TextInput::make('number')
                            ->label('BAPP Number')
                            ->disabled()
                            ->dehydrated(false)
                            ->placeholder('WCR-YYYYMM-XXXX'),
                        DatePicker::make('document_date')
                            ->label('Document Date')
                            ->placeholder('Select date')
                            ->helperText('The official date this report was created.')
                            ->required()
                            ->default(now()),
                        Select::make('project_id')
                            ->label('Project')
                            ->placeholder('Select project')
                            ->options(Project::all()->pluck('name', 'id'))
                            ->searchable()
                            ->required()
                            ->live(),
                        Select::make('customer_id')
                            ->label('Customer')
                            ->placeholder('Select customer')
                            ->options(Customer::all()->pluck('name', 'id'))
                            ->searchable()
                            ->required(),
                    ])->columns(2)
                    ->columnSpanFull()
                    ->collapsible(),

                Section::make('Source Document')
                    ->description('Select the primary document this BAPP is based on.')
                    ->schema([
                        MorphToSelect::make('sourceable')
                            ->label('Reference Document')
                            ->types([
                                MorphToSelect\Type::make(SalesOrder::class)
                                    ->titleAttribute('number')
                                    ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->number} - {$record->customer?->name}"),
                                MorphToSelect\Type::make(PurchaseOrder::class)
                                    ->titleAttribute('number')
                                    ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->number} - {$record->customer?->name}"),
                                MorphToSelect\Type::make(WorkOrder::class)
                                    ->titleAttribute('number')
                                    ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->number} - {$record->customer?->name}"),
                                MorphToSelect\Type::make(CooperationAgreement::class)
                                    ->titleAttribute('number')
                                    ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->number} - {$record->customer?->name}"),
                                MorphToSelect\Type::make(MinutesOfAgreement::class)
                                    ->titleAttribute('number')
                                    ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->number} - {$record->customer?->name}"),
                                MorphToSelect\Type::make(WorkCompletionReport::class)
                                    ->titleAttribute('number'),
                            ])
                            ->searchable()
                            ->preload()
                            ->live()
                            ->afterStateUpdated(function (Get $get, Set $set, $state) {
                                if (! $state) {
                                    return;
                                }

                                if (is_array($state)) {
                                    $modelClass = $state['type'] ?? null;
                                    $id = $state['id'] ?? null;
                                } else {
                                    [$modelClass, $id] = explode(':', $state);
                                }

                                if (! $modelClass || ! $id) {
                                    return;
                                }

                                $source = $modelClass::find($id);

                                if (! $source) {
                                    return;
                                }

                                if (isset($source->customer_id)) {
                                    $set('customer_id', $source->customer_id);
                                }

                                if ($source instanceof SalesOrder) {
                                    $set('so_type', $source->type->value);

                                    $manpower = $source->content_config['manpower_details'] ?? [];
                                    $operational = $source->content_config['items'] ?? [];
                                    $mfRate = (float) ($source->management_fee_percentage ?? 0);

                                    $items = [];
                                    $totalCost = 0;

                                    foreach ($manpower as $mp) {
                                        $cost = (float) ($mp['unit_cost'] ?? 0);
                                        $qty = (float) ($mp['quantity'] ?? 0);
                                        $total = $cost * $qty;
                                        $totalCost += $total;

                                        $feeForThisItem = ($mfRate > 0) ? round(($cost / (1 - ($mfRate / 100))) - $cost, 0) : 0;
                                        $sellingPrice = $cost + $feeForThisItem;

                                        $items[] = [
                                            'item_name' => $mp['job_position_name'] ?? 'Personnel',
                                            'ukuran_pekerjaan' => $mp['job_position_name'] ?? '-',
                                            'quantity' => $qty,
                                            'uom' => $mp['uom'] ?? 'Person',
                                            'unit_price' => $sellingPrice,
                                            'total_price' => $sellingPrice * $qty,
                                            'management_fee' => $feeForThisItem * $qty,
                                            'so_reference' => $source->type->value === SalesOrderType::Internal->value ? '-' : $source->number,
                                            'keterangan' => null,
                                        ];
                                    }

                                    foreach ($operational as $op) {
                                        $cost = (float) ($op['unit_cost'] ?? 0);
                                        $qty = (float) ($op['quantity'] ?? 0);
                                        $total = $cost * $qty;
                                        $totalCost += $total;

                                        $feeForThisItem = ($mfRate > 0) ? round(($cost / (1 - ($mfRate / 100))) - $cost, 0) : 0;
                                        $items[] = [
                                            'item_name' => $op['item_name'] ?? 'Item',
                                            'ukuran_pekerjaan' => $op['description'] ?? $op['item_name'] ?? '-',
                                            'quantity' => $qty,
                                            'uom' => $op['uom'] ?? 'Unit',
                                            'unit_price' => $cost,
                                            'total_price' => $total,
                                            'management_fee' => $feeForThisItem ?? 0,
                                            'so_reference' => $source->type->value === SalesOrderType::Internal->value ? '-' : $source->number,
                                            'keterangan' => null,
                                        ];
                                    }

                                    // 3. Add Management Fee if applicable
                                    if ($mfRate > 0) {
                                        // Formula: Revenue = Cost / (1 - Margin)
                                        // Fee = Revenue - Cost
                                        $revenue = ($mfRate < 100) ? ($totalCost / (1 - ($mfRate / 100))) : ($totalCost * 1.15);
                                        $feeAmount = round($revenue - $totalCost, 0);

                                        $items[] = [
                                            'item_name' => 'Management Fee',
                                            'ukuran_pekerjaan' => 'Management Fee ('.$mfRate.'%)',
                                            'quantity' => 1,
                                            'uom' => 'Lot',
                                            'unit_price' => $feeAmount,
                                            'total_price' => $feeAmount,
                                            'so_reference' => $source->type->value === SalesOrderType::Internal->value ? '-' : $source->number,
                                            'keterangan' => null,
                                        ];
                                    }

                                    $set('items', [
                                        'id' => $items,
                                        'en' => $items,
                                    ]);
                                    $taxRate = (int) ($source->tax_percentage ?? 12);
                                    $set('tax_percentage', $source->type->value === SalesOrderType::Internal->value ? '0' : (string) $taxRate);

                                    $set('tax_wording', $source->type->value === SalesOrderType::Internal->value
                                        ? ['id' => '-', 'en' => '-']
                                        : [
                                            'id' => "Penyelesaian pekerjaan di atas belum termasuk PPN {$taxRate}%",
                                            'en' => "The above work completion does not include {$taxRate}% VAT",
                                        ]
                                    );

                                    $set('description', [
                                        'id' => "Laporan Penyelesaian Pekerjaan untuk {$source->number}",
                                        'en' => "Work Completion Report for {$source->number}",
                                    ]);

                                    $set('content_config', [
                                        'management_fee_percentage' => $mfRate,
                                        'management_fee_amount' => $feeAmount ?? 0,
                                        'total_cost' => $totalCost,
                                    ]);
                                } else {
                                    $set('so_type', 'External');
                                    if (isset($source->items)) {
                                        $set('items', $source->items);
                                    }
                                }
                            })
                            ->columnSpanFull(),
                    ])
                    ->collapsible(),

                Section::make('Customer Signatory')
                    ->description('Identify the external person who will represent the customer for signing.')
                    ->schema([
                        Select::make('recipient_contact_index')
                            ->label('Customer Contact Reference')
                            ->options(function (Get $get) {
                                $customerId = $get('customer_id');
                                if (! $customerId) {
                                    return [];
                                }
                                $customer = Customer::find($customerId);
                                if (! $customer || empty($customer->contacts)) {
                                    return [];
                                }

                                return collect($customer->contacts)
                                    ->mapWithKeys(function ($contact, $index) {
                                        $label = $contact['name'] ?? 'Unknown';
                                        $pos = $contact['position'] ?? $contact['job_position'] ?? $contact['role'] ?? $contact['type'] ?? 'No Position';

                                        return [$index => "{$label} ({$pos})"];
                                    })
                                    ->toArray();
                            })
                            ->live()
                            ->afterStateUpdated(function ($state, Set $set, Get $get) {
                                if ($state === null || $state === '') {
                                    return;
                                }
                                $customerId = $get('customer_id');
                                if (! $customerId) {
                                    return;
                                }
                                $customer = Customer::find($customerId);
                                if (! $customer || empty($customer->contacts)) {
                                    return;
                                }
                                $contact = $customer->contacts[$state] ?? null;
                                if ($contact) {
                                    $set('content_config.recipient_name', $contact['name'] ?? '');

                                    $position = $contact['position'] ??
                                               $contact['job_position'] ??
                                               $contact['job_title'] ??
                                               $contact['role'] ??
                                               $contact['type'] ??
                                               '';

                                    // If position is a UUID (from type field), we don't want to show it as a title
                                    if (preg_match('/^[0-9a-f]{8}-\b[0-9a-f]{4}\b-\b[0-9a-f]{4}\b-\b[0-9a-f]{4}\b-\b[0-9a-f]{12}\b$/i', $position)) {
                                        $position = '';
                                    }

                                    $set('content_config.recipient_title', $position);
                                    $set('content_config.recipient_gender', $contact['gender'] ?? Gender::Male->value);
                                }
                            })
                            ->createOptionForm([
                                Grid::make(3)->schema([
                                    Select::make('gender')
                                        ->options(Gender::class)
                                        ->required()
                                        ->native(false),
                                    TextInput::make('name')->required(),
                                    TextInput::make('job_position')->label('Job Position'),
                                ]),
                                Grid::make(2)->schema([
                                    TextInput::make('email')->email(),
                                    TextInput::make('phone')->tel(),
                                ]),
                            ])
                            ->createOptionUsing(function (array $data, Get $get) {
                                $customerId = $get('customer_id');
                                if (! $customerId) {
                                    return null;
                                }
                                $customer = Customer::find($customerId);
                                if (! $customer) {
                                    return null;
                                }

                                $contacts = $customer->contacts ?? [];
                                $contacts[] = [
                                    'gender' => $data['gender'],
                                    'name' => $data['name'],
                                    'job_position' => $data['job_position'],
                                    'email' => $data['email'] ?? null,
                                    'phone' => $data['phone'] ?? null,
                                    'type' => null,
                                ];

                                $customer->contacts = $contacts;
                                $customer->save();

                                return count($contacts) - 1;
                            })
                            ->placeholder('Pick a contact to auto-fill...')
                            ->dehydrated(false)
                            ->helperText('Selecting a contact will populate the fields below for the signing party.'),

                        Grid::make(3)->schema([
                            Select::make('content_config.recipient_gender')
                                ->label('Salutation')
                                ->options(Gender::class)
                                ->required()
                                ->native(false)
                                ->placeholder('Select gender'),

                            TextInput::make('content_config.recipient_name')
                                ->label('Recipient Name')
                                ->placeholder('Full name of the signatory')
                                ->required(),

                            TextInput::make('content_config.recipient_title')
                                ->label('Recipient Title/Position')
                                ->placeholder('e.g. Operation Manager'),
                        ]),
                    ])
                    ->collapsible(),

                Section::make('Service & Progress')
                    ->description('Define the time period and the percentage of work completed.')
                    ->schema([
                        DatePicker::make('service_period_start')
                            ->label('Service Period Start')
                            ->placeholder('Select start date')
                            ->helperText('The beginning date of the work being reported.')
                            ->required(),
                        DatePicker::make('service_period_end')
                            ->label('Service Period End')
                            ->placeholder('Select end date')
                            ->helperText('The ending date of the work being reported.')
                            ->required(),
                        TextInput::make('work_progress_percentage')
                            ->label('Work Progress')
                            ->numeric()
                            ->suffix('%')
                            ->placeholder('100')
                            ->helperText('The total progress of the project as of this report.')
                            ->required()
                            ->default(100),
                        Select::make('status')
                            ->label('Report Status')
                            ->options(WorkCompletionStatus::class)
                            ->required()
                            ->default(WorkCompletionStatus::Draft)
                            ->disabled()
                            ->dehydrated(),
                    ])->columns(2)
                    ->collapsible(),

                Section::make('Additional Information')
                    ->schema([
                        TextInput::make('so_type')
                            ->hidden()
                            ->dehydrated(false),
                        Textarea::make('description')
                            ->columnSpanFull()
                            ->translatable(),
                    ])->columns(2)
                    ->collapsible(),

                Section::make('BAPP Line Items')
                    ->description('Detailed breakdown of work completed based on the Sales Order.')
                    ->schema([
                        Repeater::make('items')
                            ->label('Line Items')
                            ->schema([
                                Grid::make(3)
                                    ->schema([
                                        TextInput::make('item_name')
                                            ->label('Item Name (Internal)')
                                            ->required()
                                            ->columnSpan(2),
                                        TextInput::make('ukuran_pekerjaan')
                                            ->label('Ukuran Pekerjaan (Report)')
                                            ->placeholder('e.g. Pembersihan Area A')
                                            ->required()
                                            ->columnSpan(1),
                                        TextInput::make('so_reference')
                                            ->label('SO Reference')
                                            ->disabled(),
                                        TextInput::make('quantity')
                                            ->label('Quantity')
                                            ->numeric()
                                            ->required()
                                            ->live(onBlur: true)
                                            ->afterStateUpdated(fn ($get, $set) => $set('total_price', round(floatval($get('quantity') ?? 0) * floatval($get('unit_price') ?? 0)))),
                                        TextInput::make('uom')
                                            ->label('Unit')
                                            ->required(),
                                        TextInput::make('unit_price')
                                            ->label('Price / Unit')
                                            ->numeric()
                                            ->currencyMask(thousandSeparator: '.', decimalSeparator: ',', precision: 0)
                                            ->prefix('IDR')
                                            ->required()
                                            ->live(onBlur: true)
                                            ->afterStateUpdated(fn ($get, $set) => $set('total_price', round(floatval($get('quantity') ?? 0) * floatval($get('unit_price') ?? 0)))),
                                        TextInput::make('total_price')
                                            ->label('Total Price')
                                            ->numeric()
                                            ->currencyMask(thousandSeparator: '.', decimalSeparator: ',', precision: 0)
                                            ->prefix('IDR')
                                            ->readonly(),
                                        TextInput::make('keterangan')
                                            ->label('Keterangan')
                                            ->placeholder('Catatan tambahan...')
                                            ->columnSpanFull(),
                                        TextInput::make('management_fee')
                                            ->hidden()
                                            ->dehydrated(),
                                    ]),
                            ])
                            ->columnSpanFull()
                            ->reorderable()
                            ->addActionLabel('Add Manual Entry')
                            ->translatable(),
                    ])->columnSpanFull()->collapsible(),
                Section::make('Tax Configuration')
                    ->description('Set the VAT percentage and official tax wording for the report.')
                    ->schema([
                        Grid::make(3)->schema([
                            Select::make('tax_percentage')
                                ->label('VAT Percentage')
                                ->options([
                                    '12' => 'PPN 12%',
                                    '11' => 'PPN 11%',
                                ])
                                ->default('12')
                                ->live()
                                ->afterStateUpdated(function ($state, $set, $get) {
                                    $baseAmount = (float) ($get('tax_base_amount') ?? 0);
                                    $taxPercent = (float) ($state ?? 12);
                                    $set('tax_amount', round($baseAmount * ($taxPercent / 100)));
                                    
                                    $set('tax_wording', [
                                        'id' => "Penyelesaian pekerjaan di atas belum termasuk PPN {$state}%",
                                        'en' => "The above work completion does not include {$state}% VAT",
                                    ]);
                                }),

                            Select::make('tax_basis')
                                ->label('Tax Basis (DPP)')
                                ->options([
                                    'total' => 'Total Amount',
                                    'management_fee' => 'Management Fee Only',
                                    'custom' => 'Custom / Manual',
                                ])
                                ->default('total')
                                ->live()
                                ->required()
                                ->afterStateUpdated(function ($state, Set $set, Get $get) {
                                    $totalAmount = collect($get('items'))->sum('total_price');
                                    $baseAmount = $totalAmount;

                                    if ($state === 'management_fee') {
                                        $items = $get('items') ?? [];
                                        $activeItems = is_array($items) && isset($items['id']) ? $items['id'] : $items;
                                        
                                        $mfSum = collect($activeItems)->filter(function ($item) {
                                            $name = strtolower($item['item_name'] ?? '');
                                            return str_contains($name, 'management fee') || str_contains($name, 'fee');
                                        })->sum(function ($item) {
                                            return is_numeric($item['total_price']) ? (float)$item['total_price'] : 0;
                                        });
                                        
                                        $baseAmount = $mfSum;
                                    } elseif ($state === 'custom') {
                                        $baseAmount = $get('tax_base_amount') ?? 0;
                                    }

                                    $set('tax_base_amount', $baseAmount);
                                    
                                    $taxPercent = (float) ($get('tax_percentage') ?? 12);
                                    $set('tax_amount', round($baseAmount * ($taxPercent / 100)));
                                }),

                            TextInput::make('tax_base_amount')
                                ->label('Taxable Amount (DPP)')
                                ->numeric()
                                ->prefix('IDR')
                                ->currencyMask(thousandSeparator: '.', decimalSeparator: ',', precision: 0)
                                ->required()
                                ->live(onBlur: true)
                                ->readOnly(fn (Get $get) => $get('tax_basis') !== 'custom')
                                ->afterStateUpdated(function ($state, Set $set, Get $get) {
                                    $baseAmount = ! is_string($state) ? (float) ($state ?? 0) : (float) str_replace(',', '.', str_replace('.', '', $state));
                                    $taxPercent = (float) ($get('tax_percentage') ?? 12);
                                    $set('tax_amount', round($baseAmount * ($taxPercent / 100)));
                                }),
                        ]),

                        TextInput::make('tax_wording')
                            ->label('Official Tax Wording')
                            ->placeholder('e.g. The above work completion does not include 12% VAT')
                            ->default(fn () => [
                                'id' => 'Penyelesaian pekerjaan di atas belum termasuk PPN 12%',
                                'en' => 'The above work completion does not include 12% VAT',
                            ])
                            ->helperText('This text will appear on the generated document.')
                            ->required()
                            ->translatable(),
                    ]),

                Section::make('Summary')
                    ->description('Review the calculated grand total of all report line items.')
                    ->schema([
                        Grid::make(3)->schema([
                            TextInput::make('total_amount')
                                ->label('Base Amount (Gross)')
                                ->numeric()
                                ->prefix('IDR')
                                ->currencyMask(thousandSeparator: '.', decimalSeparator: ',', precision: 0)
                                ->readonly()
                                ->live()
                                ->afterStateHydrated(function ($set, $get) {
                                    $sum = collect($get('items'))->sum('total_price');
                                    $set('total_amount', $sum);
                                    
                                    // If tax_base_amount is not set, default to total
                                    if (! $get('tax_base_amount')) {
                                        $set('tax_base_amount', $sum);
                                        $taxPercent = (float) ($get('tax_percentage') ?? 12);
                                        $set('tax_amount', round($sum * ($taxPercent / 100)));
                                    }
                                }),

                            TextInput::make('tax_amount')
                                ->label('Tax Amount (VAT)')
                                ->numeric()
                                ->prefix('IDR')
                                ->currencyMask(thousandSeparator: '.', decimalSeparator: ',', precision: 0)
                                ->readonly(),

                            TextInput::make('grand_total')
                                ->label('Grand Total')
                                ->numeric()
                                ->prefix('IDR')
                                ->currencyMask(thousandSeparator: '.', decimalSeparator: ',', precision: 0)
                                ->readonly()
                                ->placeholder('0')
                                ->state(fn (Get $get) => (float)($get('total_amount') ?? 0) + (float)($get('tax_amount') ?? 0)),
                        ]),
                    ]),

            ]);
    }
}
