<?php

namespace Modules\Project\Filament\Clusters\Project\Resources\Projects\Resources\WorkCompletionReports\Schemas;

use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\Hidden;
use Filament\Forms\Components\MorphToSelect;
use Filament\Forms\Components\Repeater;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\SpatieMediaLibraryFileUpload;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Components\Grid;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Components\Utilities\Set;
use Filament\Schemas\Schema;
use Modules\CRM\Enums\SalesOrderType;
use Modules\CRM\Models\CooperationAgreement;
use Modules\CRM\Models\Customer;
use Modules\CRM\Models\MinutesOfAgreement;
use Modules\CRM\Models\PurchaseOrder;
use Modules\CRM\Models\SalesOrder;
use Modules\CRM\Models\WorkOrder;
use Modules\MasterData\Enums\Gender;
use Modules\MasterData\Models\ProjectArea;
use Modules\MasterData\Models\Tax;
use Modules\Project\Enums\WorkCompletionStatus;
use Modules\Project\Models\Project;
use Modules\Project\Models\WorkCompletionReport;

class WorkCompletionReportForm
{
    private static function parseNumber($value): float
    {
        if (is_numeric($value)) {
            return (float) $value;
        }

        if (! is_string($value)) {
            return 0;
        }

        return (float) str_replace(',', '.', str_replace('.', '', $value));
    }

    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Hidden::make('snapshot'),
                Section::make('Documents')
                    ->description('Download the draft report for signing, and upload the final scanned version to complete the workflow.')
                    ->schema([
                        Grid::make(2)
                            ->schema([
                                SpatieMediaLibraryFileUpload::make('draft_report')
                                    ->label('Draft BAPP (Unsigned)')
                                    ->collection('draft_report')
                                    ->disk('s3')
                                    ->downloadable()
                                    ->openable()
                                    ->placeholder('System-generated draft')
                                    ->helperText('This document is automatically generated by the system for signing purposes.'),

                                SpatieMediaLibraryFileUpload::make('signed_report')
                                    ->label('Signed BAPP (Final Scan)')
                                    ->collection('signed_report')
                                    ->disk('s3')
                                    ->downloadable()
                                    ->openable()
                                    ->placeholder('Upload scanned signature')
                                    ->helperText('Upload the final scanned document that has been signed by all relevant parties.')
                                    ->required(fn (Get $get) => $get('status') === WorkCompletionStatus::Submitted->value &&
                                        $get('so_type') !== \Modules\CRM\Enums\SalesOrderType::Internal->value
                                    ),
                            ]),
                    ])->columnSpanFull()
                    ->collapsible(),

                Section::make('Report Details')
                    ->description('Specify the basic information for this Work Completion Report.')
                    ->schema([
                        TextInput::make('number')
                            ->label('BAPP Number')
                            ->disabled()
                            ->dehydrated(false)
                            ->placeholder('WCR-YYYYMM-XXXX'),
                        DatePicker::make('document_date')
                            ->label('Document Date')
                            ->placeholder('Select date')
                            ->helperText('The official date this report was created.')
                            ->required()
                            ->default(now()),
                        Select::make('project_id')
                            ->label('Project')
                            ->options(Project::all()->mapWithKeys(fn ($p) => [$p->id => "{$p->number} - {$p->name}"]))
                            ->searchable()
                            ->required()
                            ->live()
                            ->placeholder('Select project')
                            ->helperText('The project this report is associated with.')
                            ->afterStateUpdated(function ($state, Set $set, Get $get) {
                                if (! $state) {
                                    return;
                                }

                                $project = Project::find($state);
                                if ($project?->lead?->industrialSector?->name === 'FMCG') {
                                    $set('tax_percentage', '11');

                                    // Update related fields
                                    $baseAmount = self::parseNumber($get('tax_base_amount'));
                                    $set('tax_amount', round($baseAmount * 0.11));
                                    $set('tax_wording', [
                                        'id' => 'Penyelesaian pekerjaan di atas belum termasuk PPN 11%',
                                        'en' => 'The above work completion does not include 11% VAT',
                                    ]);
                                }
                            }),
                        Select::make('customer_id')
                            ->label('Customer')
                            ->options(Customer::all()->pluck('name', 'id'))
                            ->searchable()
                            ->required()
                            ->placeholder('Select customer')
                            ->helperText('The customer entity involved in this project.'),
                        Select::make('project_area_id')
                            ->label('Project Area')
                            ->options(ProjectArea::all()->pluck('name', 'id'))
                            ->searchable()
                            ->placeholder('Select area')
                            ->helperText('The geographical area or segment this BAPP belongs to.'),
                    ])->columns(3)
                    ->columnSpanFull()
                    ->collapsible(),

                Section::make('Source Document')
                    ->description('Select the primary document this BAPP is based on.')
                    ->schema([
                        MorphToSelect::make('sourceable')
                            ->label('Reference Document')
                            ->types([
                                MorphToSelect\Type::make(SalesOrder::class)
                                    ->label('Sales Order (SO)')
                                    ->titleAttribute('number')
                                    ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->number} - {$record->customer?->name}"),
                                MorphToSelect\Type::make(PurchaseOrder::class)
                                    ->label('Purchase Order (PO)')
                                    ->titleAttribute('number')
                                    ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->number} - {$record->customer?->name}"),
                                MorphToSelect\Type::make(WorkOrder::class)
                                    ->label('Work Order (SPK)')
                                    ->titleAttribute('number')
                                    ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->number} - {$record->customer?->name}"),
                                MorphToSelect\Type::make(CooperationAgreement::class)
                                    ->label('Cooperation Agreement (PKS)')
                                    ->titleAttribute('number')
                                    ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->number} - {$record->customer?->name}"),
                                MorphToSelect\Type::make(MinutesOfAgreement::class)
                                    ->label('Minutes of Agreement (MOA)')
                                    ->titleAttribute('number')
                                    ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->number} - {$record->customer?->name}"),
                                MorphToSelect\Type::make(WorkCompletionReport::class)
                                    ->label('Work Completion Report (BAPP)')
                                    ->titleAttribute('number'),
                            ])
                            ->searchable()
                            ->preload()
                            ->live()
                            ->afterStateUpdated(function (Get $get, Set $set, $state) {
                                if (! $state) {
                                    return;
                                }

                                if (is_array($state)) {
                                    $modelClass = $state['type'] ?? null;
                                    $id = $state['id'] ?? null;
                                } else {
                                    [$modelClass, $id] = explode(':', $state);
                                }

                                if (! $modelClass || ! $id) {
                                    return;
                                }

                                $source = $modelClass::find($id);

                                if (! $source) {
                                    return;
                                }

                                if (isset($source->customer_id)) {
                                    $set('customer_id', $source->customer_id);
                                }

                                if (isset($source->project_area_id)) {
                                    $set('project_area_id', $source->project_area_id);
                                } elseif (isset($source->project?->project_area_id)) {
                                    $set('project_area_id', $source->project->project_area_id);
                                }

                                if ($source instanceof SalesOrder) {
                                    $set('so_type', $source->type->value);
                                    $set('tax_id', $source->tax_id);
                                    $set('tax_percentage', (string) ($source->tax_percentage ?? 12));
                                    $set('snapshot', $source->snapshot);

                                    $manpower = $source->snapshot['groups']['manpower'] ?? $source->content_config['manpower_details'] ?? [];
                                    $operational = $source->snapshot['groups']['operational'] ?? $source->content_config['items'] ?? [];
                                    $mfRate = (float) ($source->management_fee_percentage ?? 0);

                                    $items = [];
                                    $totalCost = 0;

                                    foreach ($manpower as $mp) {
                                        $sellingPrice = (float) ($mp['unit_price'] ?? 0);
                                        $cost = (float) ($mp['unit_cost'] ?? 0);
                                        $qty = (float) ($mp['quantity'] ?? 0);
                                        $totalCost += ($cost * $qty);

                                        if ($sellingPrice <= 0) {
                                            $feeForThisItem = ($mfRate > 0) ? round(($cost / (1 - ($mfRate / 100))) - $cost, 0) : 0;
                                            $sellingPrice = $cost + $feeForThisItem;
                                        } else {
                                            $feeForThisItem = ($sellingPrice - $cost);
                                        }

                                        $items[] = [
                                            'item_name' => $mp['job_position_name'] ?? 'Personnel',
                                            'work_measurement' => $mp['job_position_name'] ?? '-',
                                            'quantity' => $qty,
                                            'uom' => $mp['uom'] ?? 'Person',
                                            'unit_price' => round($sellingPrice, 0),
                                            'total_price' => round($sellingPrice * $qty, 0),
                                            'management_fee' => round($feeForThisItem * $qty, 0),
                                            'so_reference' => $source->type->value === SalesOrderType::Internal->value ? '-' : $source->number,
                                            'remarks' => null,
                                        ];
                                    }

                                    foreach ($operational as $op) {
                                        $sellingPrice = (float) ($op['unit_price'] ?? 0);
                                        $cost = (float) ($op['unit_cost'] ?? 0);
                                        $qty = (float) ($op['quantity'] ?? 0);
                                        $totalCost += ($cost * $qty);

                                        if ($sellingPrice <= 0) {
                                            $feeForThisItem = ($mfRate > 0) ? round(($cost / (1 - ($mfRate / 100))) - $cost, 0) : 0;
                                            $sellingPrice = $cost + $feeForThisItem;
                                        } else {
                                            $feeForThisItem = ($sellingPrice - $cost);
                                        }

                                        $items[] = [
                                            'item_name' => $op['item_name'] ?? 'Item',
                                            'work_measurement' => $op['description'] ?? $op['item_name'] ?? '-',
                                            'quantity' => $qty,
                                            'uom' => $op['uom'] ?? 'Unit',
                                            'unit_price' => round($sellingPrice, 0),
                                            'total_price' => round($sellingPrice * $qty, 0),
                                            'management_fee' => round($feeForThisItem * $qty, 0),
                                            'so_reference' => $source->type->value === SalesOrderType::Internal->value ? '-' : $source->number,
                                            'remarks' => null,
                                        ];
                                    }

                                    // 3. Management Fee summary
                                    $totalFeeAmount = collect($items)->sum('management_fee');

                                    // We don't add a separate Management Fee line item if it's already spread in prices
                                    // But we still track the total for content_config
                                    $feeAmount = $totalFeeAmount;

                                    $set('items', [
                                        'id' => $items,
                                        'en' => $items,
                                    ]);
                                    $taxRate = (int) ($source->tax_percentage ?? 12);
                                    $set('tax_percentage', $source->type->value === SalesOrderType::Internal->value ? '0' : (string) $taxRate);

                                    $set('tax_wording', $source->type->value === SalesOrderType::Internal->value
                                        ? ['id' => '-', 'en' => '-']
                                        : [
                                            'id' => "Penyelesaian pekerjaan di atas belum termasuk PPN {$taxRate}%",
                                            'en' => "The above work completion does not include {$taxRate}% VAT",
                                        ]
                                    );

                                    $set('description', [
                                        'id' => "Laporan Penyelesaian Pekerjaan untuk {$source->number}",
                                        'en' => "Work Completion Report for {$source->number}",
                                    ]);

                                    $set('content_config', [
                                        'management_fee_percentage' => $mfRate,
                                        'management_fee_amount' => $feeAmount ?? 0,
                                        'total_cost' => $totalCost,
                                    ]);
                                } else {
                                    $set('so_type', 'External');
                                    if (isset($source->items)) {
                                        $set('items', $source->items);
                                    }
                                }
                            })
                            ->columnSpanFull(),
                    ])
                    ->collapsible(),

                Section::make('Customer Signatory')
                    ->description('Identify the external person who will represent the customer for signing.')
                    ->schema([
                        Select::make('recipient_contact_index')
                            ->label('Customer Contact Reference')
                            ->options(function (Get $get) {
                                $customerId = $get('customer_id');
                                if (! $customerId) {
                                    return [];
                                }
                                $customer = Customer::find($customerId);
                                if (! $customer || empty($customer->contacts)) {
                                    return [];
                                }

                                return collect($customer->contacts)
                                    ->mapWithKeys(function ($contact, $index) {
                                        $label = $contact['name'] ?? 'Unknown';
                                        $pos = $contact['position'] ?? $contact['job_position'] ?? $contact['role'] ?? $contact['type'] ?? 'No Position';

                                        return [$index => "{$label} ({$pos})"];
                                    })
                                    ->toArray();
                            })
                            ->live()
                            ->afterStateUpdated(function ($state, Set $set, Get $get) {
                                if ($state === null || $state === '') {
                                    return;
                                }
                                $customerId = $get('customer_id');
                                if (! $customerId) {
                                    return;
                                }
                                $customer = Customer::find($customerId);
                                if (! $customer || empty($customer->contacts)) {
                                    return;
                                }
                                $contact = $customer->contacts[$state] ?? null;
                                if ($contact) {
                                    $set('content_config.recipient_name', $contact['name'] ?? '');

                                    $position = $contact['position'] ??
                                               $contact['job_position'] ??
                                               $contact['job_title'] ??
                                               $contact['role'] ??
                                               $contact['type'] ??
                                               '';

                                    // If position is a UUID (from type field), we don't want to show it as a title
                                    if (preg_match('/^[0-9a-f]{8}-\b[0-9a-f]{4}\b-\b[0-9a-f]{4}\b-\b[0-9a-f]{4}\b-\b[0-9a-f]{12}\b$/i', $position)) {
                                        $position = '';
                                    }

                                    $set('content_config.recipient_title', $position);
                                    $set('content_config.recipient_gender', $contact['gender'] ?? Gender::Male->value);
                                }
                            })
                            ->createOptionForm([
                                Grid::make(3)->schema([
                                    Select::make('gender')
                                        ->options(Gender::class)
                                        ->required()
                                        ->native(false),
                                    TextInput::make('name')->required(),
                                    TextInput::make('job_position')->label('Job Position'),
                                ]),
                                Grid::make(2)->schema([
                                    TextInput::make('email')->email(),
                                    TextInput::make('phone')->tel(),
                                ]),
                            ])
                            ->createOptionUsing(function (array $data, Get $get) {
                                $customerId = $get('customer_id');
                                if (! $customerId) {
                                    return null;
                                }
                                $customer = Customer::find($customerId);
                                if (! $customer) {
                                    return null;
                                }

                                $contacts = $customer->contacts ?? [];
                                $contacts[] = [
                                    'gender' => $data['gender'],
                                    'name' => $data['name'],
                                    'job_position' => $data['job_position'],
                                    'email' => $data['email'] ?? null,
                                    'phone' => $data['phone'] ?? null,
                                    'type' => null,
                                ];

                                $customer->contacts = $contacts;
                                $customer->save();

                                return count($contacts) - 1;
                            })
                            ->placeholder('Pick a contact to auto-fill...')
                            ->dehydrated(false)
                            ->helperText('Selecting a contact will populate the fields below for the signing party.'),

                        Grid::make(3)->schema([
                            Select::make('content_config.recipient_gender')
                                ->label('Salutation')
                                ->options(Gender::class)
                                ->required()
                                ->native(false)
                                ->placeholder('Select gender')
                                ->helperText('Gender-based salutation for the recipient (Bapak/Ibu).'),

                            TextInput::make('content_config.recipient_name')
                                ->label('Recipient Name')
                                ->placeholder('Full name of the signatory')
                                ->helperText('The name of the individual who will sign on behalf of the customer.')
                                ->required(),

                            TextInput::make('content_config.recipient_title')
                                ->label('Recipient Title/Position')
                                ->placeholder('e.g. Operation Manager')
                                ->helperText('Official job title of the signatory.'),
                        ]),
                    ])
                    ->collapsible(),

                Section::make('Service & Progress')
                    ->description('Define the time period and the percentage of work completed.')
                    ->schema([
                        DatePicker::make('service_period_start')
                            ->label('Service Period Start')
                            ->placeholder('Select start date')
                            ->helperText('The beginning date of the work being reported.')
                            ->required(),
                        DatePicker::make('service_period_end')
                            ->label('Service Period End')
                            ->placeholder('Select end date')
                            ->helperText('The ending date of the work being reported.')
                            ->required(),
                        TextInput::make('work_progress_percentage')
                            ->label('Work Progress')
                            ->numeric()
                            ->suffix('%')
                            ->placeholder('100')
                            ->helperText('The total progress of the project as of this report.')
                            ->required()
                            ->default(100),
                        Select::make('status')
                            ->label('Report Status')
                            ->options(WorkCompletionStatus::class)
                            ->required()
                            ->default(WorkCompletionStatus::Draft)
                            ->disabled()
                            ->dehydrated(),
                    ])->columns(2)
                    ->collapsible(),

                Section::make('Additional Information')
                    ->schema([
                        TextInput::make('so_type')
                            ->hidden()
                            ->dehydrated(false),
                        Textarea::make('description')
                            ->columnSpanFull()
                            ->translatable(),
                    ])->columns(2)
                    ->collapsible(),

                Section::make('BAPP Line Items')
                    ->description('Detailed breakdown of work completed based on the Sales Order.')
                    ->schema([
                        Repeater::make('items')
                            ->label('Line Items')
                            ->live()
                            ->afterStateUpdated(function (Set $set, Get $get) {
                                $basis = $get('tax_basis') ?? 'total';
                                if ($basis === 'custom') {
                                    return;
                                }

                                $items = $get('items') ?? [];
                                $activeItems = is_array($items) && isset($items['id']) ? $items['id'] : $items;

                                if ($basis === 'management_fee') {
                                    $mfSum = collect($activeItems)->sum(function ($item) {
                                        return is_numeric($item['management_fee'] ?? 0) ? (float) $item['management_fee'] : 0;
                                    });

                                    if ($mfSum <= 0) {
                                        $mfSum = collect($activeItems)->filter(function ($item) {
                                            $name = strtolower($item['item_name'] ?? $item['work_measurement'] ?? '');

                                            return str_contains($name, 'management fee') || str_contains($name, 'fee management');
                                        })->sum(function ($item) {
                                            return is_numeric($item['total_price'] ?? 0) ? (float) $item['total_price'] : 0;
                                        });
                                    }
                                    $baseAmount = $mfSum;
                                } else {
                                    $baseAmount = collect($activeItems)->sum(function ($item) {
                                        return is_numeric($item['total_price'] ?? 0) ? (float) $item['total_price'] : 0;
                                    });
                                }

                                $set('tax_base_amount', $baseAmount);
                            })
                            ->schema([
                                Grid::make(3)
                                    ->schema([
                                        TextInput::make('item_name')
                                            ->label('Item Name (Internal)')
                                            ->required()
                                            ->placeholder('e.g. Manpower Supply')
                                            ->helperText('Internal name for the item or service.')
                                            ->columnSpan(2),
                                        TextInput::make('work_measurement')
                                            ->label('Work Measurement (Report)')
                                            ->placeholder('e.g. Area A Cleaning')
                                            ->helperText('Description of work as it appears on the printed report.')
                                            ->required()
                                            ->columnSpan(1),
                                        TextInput::make('so_reference')
                                            ->label('SO Reference')
                                            ->disabled(),
                                        TextInput::make('quantity')
                                            ->label('Quantity')
                                            ->numeric()
                                            ->required()
                                            ->placeholder('1')
                                            ->helperText('Number of units delivered.')
                                            ->live(onBlur: true)
                                            ->afterStateUpdated(fn ($get, $set) => $set('total_price', round(floatval($get('quantity') ?? 0) * floatval($get('unit_price') ?? 0)))),
                                        TextInput::make('uom')
                                            ->label('Unit')
                                            ->required()
                                            ->placeholder('Org / Bln')
                                            ->helperText('Unit of measure.'),
                                        TextInput::make('unit_price')
                                            ->label('Price / Unit')
                                            ->numeric()
                                            ->currencyMask(thousandSeparator: '.', decimalSeparator: ',', precision: 0)
                                            ->prefix('IDR')
                                            ->required()
                                            ->placeholder('0')
                                            ->helperText('Price per single unit.')
                                            ->live(onBlur: true)
                                            ->afterStateUpdated(fn ($get, $set) => $set('total_price', round(floatval($get('quantity') ?? 0) * floatval($get('unit_price') ?? 0)))),
                                        TextInput::make('total_price')
                                            ->label('Total Price')
                                            ->numeric()
                                            ->currencyMask(thousandSeparator: '.', decimalSeparator: ',', precision: 0)
                                            ->prefix('IDR')
                                            ->readonly(),
                                        TextInput::make('remarks')
                                            ->label('Remarks')
                                            ->placeholder('Additional notes...')
                                            ->columnSpanFull(),
                                        TextInput::make('management_fee')
                                            ->hidden()
                                            ->dehydrated(),
                                    ]),
                            ])
                            ->columnSpanFull()
                            ->reorderable()
                            ->addActionLabel('Add Manual Entry')
                            ->translatable(),
                    ])->columnSpanFull()->collapsible(),
                Section::make('Tax Configuration')
                    ->description('Set the VAT percentage and official tax wording for the report.')
                    ->schema([
                        Grid::make(2)->schema([
                            Select::make('tax_id')
                                ->label('Tax Scheme (VAT/PPh)')
                                ->relationship('tax', 'name', fn ($query) => $query->where('category', 'sales')->where('is_active', true))
                                ->required()
                                ->searchable()
                                ->preload()
                                ->live()
                                ->placeholder('Select tax configuration')
                                ->helperText('The applicable tax rate (e.g., PPN 11%).')
                                ->afterStateUpdated(function ($state, Set $set, Get $get) {
                                    $rate = Tax::find($state)?->rate ?? 0;
                                    $set('tax_percentage', $rate);

                                    $set('tax_wording', [
                                        'id' => "Penyelesaian pekerjaan di atas belum termasuk PPN {$rate}%",
                                        'en' => "The above work completion does not include {$rate}% VAT",
                                    ]);
                                })
                                ->afterStateHydrated(function ($state, Set $set, Get $get) {
                                    if ($state) {
                                        $rate = Tax::find($state)?->rate ?? 0;
                                        $set('tax_percentage', $rate);

                                        // Only set wording if it's empty to avoid overwriting custom wording
                                        if (! $get('tax_wording')) {
                                            $set('tax_wording', [
                                                'id' => "Penyelesaian pekerjaan di atas belum termasuk PPN {$rate}%",
                                                'en' => "The above work completion does not include {$rate}% VAT",
                                            ]);
                                        }
                                    }
                                })
                                ->default(fn () => Tax::where('category', 'sales')->where('is_default', true)->first()?->id),

                            TextInput::make('tax_percentage')
                                ->label('Tax Rate (%)')
                                ->numeric()
                                ->readOnly()
                                ->live()
                                ->placeholder('0')
                                ->helperText('The numerical tax rate percentage.')
                                ->default(fn () => Tax::where('category', 'sales')->where('is_default', true)->first()?->rate ?? 12.00),

                            Select::make('tax_basis')
                                ->label('Tax Basis (DPP)')
                                ->options([
                                    'total' => 'Total Amount',
                                    'management_fee' => 'Management Fee Only',
                                    'custom' => 'Custom / Manual',
                                ])
                                ->default('total')
                                ->live()
                                ->required()
                                ->placeholder('Select tax calculation basis')
                                ->helperText('Choose whether tax is calculated from total amount, management fee, or entered manually.')
                                ->afterStateUpdated(function ($state, Set $set, Get $get) {
                                    $items = $get('items') ?? [];
                                    $activeItems = is_array($items) && isset($items['id']) ? $items['id'] : $items;
                                    $totalAmount = collect($activeItems)->sum('total_price');
                                    $baseAmount = $totalAmount;

                                    if ($state === 'management_fee') {
                                        $mfSum = collect($activeItems)->sum(function ($item) {
                                            return is_numeric($item['management_fee'] ?? 0) ? (float) $item['management_fee'] : 0;
                                        });

                                        if ($mfSum <= 0) {
                                            $mfSum = collect($activeItems)->filter(function ($item) {
                                                $name = strtolower($item['item_name'] ?? $item['work_measurement'] ?? '');

                                                return str_contains($name, 'management fee') || str_contains($name, 'fee management');
                                            })->sum(function ($item) {
                                                return is_numeric($item['total_price'] ?? 0) ? (float) $item['total_price'] : 0;
                                            });
                                        }

                                        $baseAmount = $mfSum;
                                    } elseif ($state === 'custom') {
                                        $baseAmount = self::parseNumber($get('tax_base_amount'));
                                    }

                                    $set('tax_base_amount', $baseAmount);

                                    $taxPercent = (float) ($get('tax_percentage') ?? 12);
                                    $set('tax_amount', round($baseAmount * ($taxPercent / 100)));
                                }),

                            TextInput::make('tax_base_amount')
                                ->label('Taxable Amount (DPP)')
                                ->numeric()
                                ->prefix('IDR')
                                ->currencyMask(thousandSeparator: '.', decimalSeparator: ',', precision: 0)
                                ->required()
                                ->live()
                                ->placeholder('0')
                                ->helperText('The amount used to calculate VAT (PPN).')
                                ->readOnly(fn (Get $get) => $get('tax_basis') !== 'custom')
                                ->afterStateHydrated(function (Set $set, Get $get) {
                                    $basis = $get('tax_basis') ?? 'total';
                                    if ($basis === 'custom') {
                                        return;
                                    }

                                    $items = $get('items') ?? [];
                                    $activeItems = is_array($items) && isset($items['id']) ? $items['id'] : $items;

                                    if ($basis === 'management_fee') {
                                        $mfSum = collect($activeItems)->sum(function ($item) {
                                            return is_numeric($item['management_fee'] ?? 0) ? (float) $item['management_fee'] : 0;
                                        });

                                        if ($mfSum <= 0) {
                                            $mfSum = collect($activeItems)->filter(function ($item) {
                                                $name = strtolower($item['item_name'] ?? $item['work_measurement'] ?? '');

                                                return str_contains($name, 'management fee') || str_contains($name, 'fee management');
                                            })->sum(function ($item) {
                                                return is_numeric($item['total_price'] ?? 0) ? (float) $item['total_price'] : 0;
                                            });
                                        }
                                        $baseAmount = $mfSum;
                                    } else {
                                        $baseAmount = collect($activeItems)->sum(function ($item) {
                                            return is_numeric($item['total_price'] ?? 0) ? (float) $item['total_price'] : 0;
                                        });
                                    }

                                    $set('tax_base_amount', $baseAmount);
                                })
                                ->afterStateUpdated(function ($state, Set $set, Get $get) {
                                    // Nothing to manually set here as summary fields are computed via state()
                                }),
                        ]),

                        TextInput::make('tax_wording')
                            ->label('Official Tax Wording')
                            ->placeholder('e.g. The above work completion does not include 12% VAT')
                            ->default(fn (Get $get) => [
                                'id' => 'Penyelesaian pekerjaan di atas belum termasuk PPN '.($get('tax_percentage') ?? '12').'%',
                                'en' => 'The above work completion does not include '.($get('tax_percentage') ?? '12').'% VAT',
                            ])
                            ->helperText('This text will appear on the generated document.')
                            ->required()
                            ->translatable(),
                    ]),

                Section::make('Summary')
                    ->description('Review the calculated grand total of all report line items.')
                    ->schema([
                        Grid::make(3)->schema([
                            TextEntry::make('total_amount')
                                ->label('Base Amount (Gross)')
                                ->state(function (Get $get): string {
                                    $items = $get('items') ?? [];
                                    $activeItems = is_array($items) && isset($items['id']) ? $items['id'] : $items;
                                    $sum = collect($activeItems)->sum(function ($item) {
                                        return is_numeric($item['total_price'] ?? 0) ? (float) $item['total_price'] : 0;
                                    });

                                    return 'IDR '.number_format($sum, 0, ',', '.');
                                }),

                            TextEntry::make('tax_amount')
                                ->label('Tax Amount (VAT)')
                                ->state(function (Get $get): string {
                                    $taxId = $get('tax_id');
                                    if (! $taxId) {
                                        return 'IDR 0';
                                    }

                                    $tax = Tax::find($taxId);
                                    if (! $tax) {
                                        return 'IDR 0';
                                    }

                                    $basis = $get('tax_basis');
                                    $items = $get('items') ?? [];
                                    $activeItems = is_array($items) && isset($items['id']) ? $items['id'] : $items;

                                    if ($basis === 'custom') {
                                        $baseAmount = self::parseNumber($get('tax_base_amount'));
                                    } elseif ($basis === 'management_fee') {
                                        $mfSum = collect($activeItems)->sum(function ($item) {
                                            return is_numeric($item['management_fee'] ?? 0) ? (float) $item['management_fee'] : 0;
                                        });

                                        if ($mfSum <= 0) {
                                            $mfSum = collect($activeItems)->filter(function ($item) {
                                                $name = strtolower($item['item_name'] ?? $item['work_measurement'] ?? '');

                                                return str_contains($name, 'management fee') || str_contains($name, 'fee management');
                                            })->sum(function ($item) {
                                                return is_numeric($item['total_price'] ?? 0) ? (float) $item['total_price'] : 0;
                                            });
                                        }
                                        $baseAmount = $mfSum;
                                    } else {
                                        $baseAmount = collect($activeItems)->sum(function ($item) {
                                            return is_numeric($item['total_price'] ?? 0) ? (float) $item['total_price'] : 0;
                                        });
                                    }

                                    $rate = (float) $tax->rate;
                                    $taxAmount = 0;

                                    if ($tax->calculation_type === 'formula') {
                                        $num = (float) ($tax->base_rate_numerator ?? 1);
                                        $den = (float) ($tax->base_rate_denominator ?? 1);
                                        $taxAmount = round($baseAmount * ($num / $den) * ($rate / 100));
                                    } elseif ($tax->calculation_type === 'inclusive') {
                                        $taxAmount = round($baseAmount * ($rate / (100 + $rate)));
                                    } else {
                                        $taxAmount = round($baseAmount * ($rate / 100));
                                    }

                                    return 'IDR '.number_format($taxAmount, 0, ',', '.');
                                }),

                            TextEntry::make('grand_total')
                                ->label('Grand Total')
                                ->state(function (Get $get): string {
                                    $items = $get('items') ?? [];
                                    $activeItems = is_array($items) && isset($items['id']) ? $items['id'] : $items;
                                    $gross = collect($activeItems)->sum(function ($item) {
                                        return is_numeric($item['total_price'] ?? 0) ? (float) $item['total_price'] : 0;
                                    });

                                    $taxId = $get('tax_id');
                                    if (! $taxId) {
                                        return 'IDR '.number_format($gross, 0, ',', '.');
                                    }

                                    $taxModel = Tax::find($taxId);
                                    if (! $taxModel) {
                                        return 'IDR '.number_format($gross, 0, ',', '.');
                                    }

                                    $basis = $get('tax_basis');
                                    if ($basis === 'custom') {
                                        $baseAmount = self::parseNumber($get('tax_base_amount'));
                                    } elseif ($basis === 'management_fee') {
                                        $baseAmount = collect($activeItems)->filter(function ($item) {
                                            $name = strtolower($item['item_name'] ?? $item['work_measurement'] ?? '');

                                            return str_contains($name, 'management fee');
                                        })->sum(function ($item) {
                                            return is_numeric($item['total_price'] ?? 0) ? (float) $item['total_price'] : 0;
                                        });
                                    } else {
                                        $baseAmount = $gross;
                                    }

                                    $rate = (float) $taxModel->rate;
                                    $taxValue = 0;

                                    if ($taxModel->calculation_type === 'formula') {
                                        $num = (float) ($taxModel->base_rate_numerator ?? 1);
                                        $den = (float) ($taxModel->base_rate_denominator ?? 1);
                                        $taxValue = round($baseAmount * ($num / $den) * ($rate / 100));
                                    } elseif ($taxModel->calculation_type === 'inclusive') {
                                        $taxValue = round($baseAmount * ($rate / (100 + $rate)));

                                        // For inclusive, the gross already contains the tax, so we don't add it?
                                        // Usually, Grand Total = Gross.
                                        return 'IDR '.number_format($gross, 0, ',', '.');
                                    } else {
                                        $taxValue = round($baseAmount * ($rate / 100));
                                    }

                                    return 'IDR '.number_format($gross + $taxValue, 0, ',', '.');
                                }),
                        ]),
                    ]),

            ]);
    }
}
