<?php

namespace Modules\CRM\Filament\Clusters\CRM\Resources\SalesOrders\Schemas;

use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\Hidden;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\SpatieMediaLibraryFileUpload;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Components\Grid;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Components\Utilities\Set;
use Filament\Schemas\Components\Wizard;
use Filament\Schemas\Components\Wizard\Step;
use Filament\Schemas\Schema;
use Illuminate\Support\HtmlString;
use Modules\CRM\Enums\ProposalStatus;
use Modules\CRM\Enums\SalesOrderStatus;
use Modules\CRM\Enums\SalesOrderType;
use Modules\Project\Models\Project;

class SalesOrderForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Wizard::make([
                    Step::make('General Information')
                        ->description('Basic project information and reference documents.')
                        ->schema([
                            Grid::make(3)
                                ->schema([
                                    TextInput::make('so_number')
                                        ->label('SO Number')
                                        ->placeholder('e.g. GDPS/UB/SO-001/26')
                                        ->helperText('The SO number is automatically generated by the system.')
                                        ->hidden(fn (string $operation): bool => $operation === 'create')
                                        ->disabled()
                                        ->unique(ignoreRecord: true),
                                    DatePicker::make('order_date')
                                        ->required()
                                        ->placeholder('Select order date')
                                        ->default(now()),
                                    Select::make('project_id')
                                        ->relationship('project', 'code')
                                        ->placeholder('Search or select project...')
                                        ->helperText('Connect with a project to automatically retrieve RAB and staffing data.')
                                        ->required()
                                        ->live()
                                        ->afterStateUpdated(function ($state, Set $set) {
                                            if (! $state) {
                                                return;
                                            }
                                            $project = Project::find($state);
                                            if ($project) {
                                                $set('customer_id', $project->customer_id);

                                                $proposal = $project->lead?->proposals()->where('status', ProposalStatus::Approved)->first();
                                                if ($proposal) {
                                                    $set('proposal_id', $proposal->id);
                                                    $set('amount', $proposal->amount);
                                                }

                                                $analysis = $project->profitabilityAnalysis;
                                                if ($analysis) {
                                                    $set('manpower_initial_qty', $analysis->total_manpower);
                                                    $set('management_fee_percentage', $analysis->management_fee_rate);
                                                    $set('tax_percentage', $analysis->tax_rate ?? 11);

                                                    // Auto-fill states from PA
                                                    $manpowerData = $analysis->manpower_requirements ?? [];
                                                    $financialData = $analysis->financial_assumptions ?? [];

                                                    $items = collect($financialData['operational_costs'] ?? [])->map(fn ($item) => [
                                                        'description' => $item['item_name'] ?? ($item['description'] ?? 'Unnamed Item'),
                                                        'uom' => $item['uom'] ?? 'Unit',
                                                        'quantity' => (float) ($item['quantity'] ?? 0),
                                                        'unit_price' => (float) ($item['unit_cost'] ?? 0),
                                                        'total_price' => (float) ($item['total_monthly_cost'] ?? 0),
                                                    ])->toArray();

                                                    $set('manpower_composition', $manpowerData);
                                                    $set('content_config', [
                                                        'items' => $items,
                                                        'manpower_details' => $manpowerData,
                                                    ]);
                                                }

                                                $lead = $project->lead;
                                                if ($lead) {
                                                    $set('sales_pic_id', $lead->ams_id);
                                                    $set('project_manager_id', $lead->oprep_id);
                                                    if (isset($analysis)) {
                                                        $set('service_type', $analysis->productCluster?->name ?? $lead->service_type);
                                                        $set('job_location', $analysis->projectArea?->name ?? $lead->job_location);
                                                    } else {
                                                        $set('service_type', $lead->service_type);
                                                        $set('job_location', $lead->job_location);
                                                    }
                                                }
                                            }
                                        }),
                                ]),
                            Grid::make(2)
                                ->schema([
                                    Select::make('customer_id')
                                        ->relationship('customer', 'name')
                                        ->placeholder('Customer will be auto-filled...')
                                        ->required()
                                        ->disabled()
                                        ->dehydrated(),
                                    Select::make('proposal_id')
                                        ->relationship('proposal', 'proposal_number')
                                        ->placeholder('Proposal will be auto-filled...')
                                        ->required()
                                        ->disabled()
                                        ->dehydrated(),
                                ]),
                            Grid::make(3)
                                ->schema([
                                    Select::make('type')
                                        ->options(SalesOrderType::class)
                                        ->default(SalesOrderType::External)
                                        ->required()
                                        ->live(),
                                ]),
                        ]),
                    Step::make('Execution & Staffing')
                        ->description('Personnel and project execution location.')
                        ->schema([
                            Grid::make(2)
                                ->schema([
                                    Select::make('sales_pic_id')
                                        ->label('Sales PIC (AMS)')
                                        ->placeholder('Select Sales Account Management...')
                                        ->relationship('salesPic', 'name')
                                        ->searchable(),
                                    Select::make('project_manager_id')
                                        ->label('Project Manager (Oprep)')
                                        ->placeholder('Select Project Manager...')
                                        ->relationship('projectManager', 'name')
                                        ->searchable(),
                                    TextInput::make('service_type')
                                        ->placeholder('e.g. Manpower Supply, Cleaning Service')
                                        ->helperText('The main type of service provided.'),
                                    TextInput::make('job_location')
                                        ->placeholder('e.g. Soekarno-Hatta Airport')
                                        ->helperText('Specific location for the project execution.'),
                                    TextInput::make('manpower_initial_qty')
                                        ->label('Initial Manpower Qty')
                                        ->numeric()
                                        ->placeholder('0')
                                        ->helperText('Total initial manpower as per contract.')
                                        ->default(0),

                                    Hidden::make('manpower_composition')
                                        ->live(),
                                    Hidden::make('content_config')
                                        ->live(),

                                    TextEntry::make('manpower_composition_preview')
                                        ->label('Personnel Deployment Overview')
                                        ->columnSpanFull()
                                        ->state(function (Get $get) {
                                            $manpower = $get('content_config.manpower_details') ?? [];
                                            if (empty($manpower)) {
                                                return new HtmlString('<div class="rounded-lg bg-gray-50 p-4 text-sm text-gray-500 italic text-center border border-dashed border-gray-300">No manpower data available. Please select a Project first.</div>');
                                            }

                                            $totalQty = 0;
                                            $totalAmount = 0;
                                            $rows = collect($manpower)->map(function ($item) use (&$totalQty, &$totalAmount) {
                                                $pos = $item['job_position_name'] ?? 'Unknown Member';
                                                $qty = (int) ($item['quantity'] ?? 0);
                                                $cost = (float) ($item['unit_cost'] ?? 0);
                                                $total = (float) ($item['total_monthly_cost'] ?? ($qty * $cost));

                                                $totalQty += $qty;
                                                $totalAmount += $total;

                                                return "
                                                <tr class='hover:bg-gray-50/50 transition-colors'>
                                                    <td class='px-4 py-2 border-b border-gray-100 text-sm font-medium text-gray-900'>{$pos}</td>
                                                    <td class='px-4 py-2 border-b border-gray-100 text-sm text-gray-600 text-right'>".number_format($qty)."</td>
                                                    <td class='px-4 py-2 border-b border-gray-100 text-sm text-gray-600 text-right'>".number_format($cost, 0, ',', '.')."</td>
                                                    <td class='px-4 py-2 border-b border-gray-100 text-sm font-semibold text-gray-900 text-right'>".number_format($total, 0, ',', '.').'</td>
                                                </tr>';
                                            })->implode('');

                                            return new HtmlString("
                                                <div class='overflow-hidden rounded-xl border border-gray-200 shadow-sm'>
                                                    <table class='w-full text-left bg-white'>
                                                        <thead>
                                                            <tr class='bg-gray-50/80'>
                                                                <th class='px-4 py-3 text-xs font-bold text-gray-500 uppercase tracking-wider border-b border-gray-200'>Position / Rank</th>
                                                                <th class='px-4 py-3 text-xs font-bold text-gray-500 uppercase tracking-wider text-right border-b border-gray-200'>Qty</th>
                                                                <th class='px-4 py-3 text-xs font-bold text-gray-500 uppercase tracking-wider text-right border-b border-gray-200'>Unit Cost</th>
                                                                <th class='px-4 py-3 text-xs font-bold text-gray-500 uppercase tracking-wider text-right border-b border-gray-200'>Total Monthly</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>{$rows}</tbody>
                                                        <tfoot class='bg-gray-50/30'>
                                                            <tr class='font-bold bg-blue-50/30'>
                                                                <td class='px-4 py-3 text-sm text-gray-900 uppercase italic font-bold'>Total Staffing Cost</td>
                                                                <td class='px-4 py-3 text-sm text-gray-900 text-right'>".number_format($totalQty)."</td>
                                                                <td class='px-4 py-3'></td>
                                                                <td class='px-4 py-3 text-sm text-blue-700 text-right font-black'>IDR ".number_format($totalAmount, 0, ',', '.').'</td>
                                                            </tr>
                                                        </tfoot>
                                                    </table>
                                                </div>
                                            ');
                                        })
                                        ->html(),
                                    TextEntry::make('manpower_attachment_preview')
                                        ->label('Original Manpower Budget File')
                                        ->columnSpanFull()
                                        ->visible(function (Get $get) {
                                            $projectId = $get('project_id');
                                            if (! $projectId) {
                                                return false;
                                            }
                                            $pa = Project::find($projectId)?->profitabilityAnalysis;

                                            return $pa && (bool) $pa->is_manual_cost;
                                        })
                                        ->state(function (Get $get) {
                                            $projectId = $get('project_id');
                                            if (! $projectId) {
                                                return null;
                                            }
                                            $pa = Project::find($projectId)?->profitabilityAnalysis;
                                            if (! $pa) {
                                                return 'PA record not found.';
                                            }
                                            $media = $pa->getFirstMedia('manpower_costing_backup');

                                            return $media
                                                ? new HtmlString("<a href='{$media->getTemporaryUrl(now()->addMinutes(60))}' target='_blank' class='text-primary-600 font-bold underline flex items-center gap-2'>
                                                    <svg class='w-4 h-4 inline-block' fill='none' stroke='currentColor' viewBox='0 0 24 24'><path stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4'></path></svg> 
                                                    Download Original Manpower Costing ({$media->file_name})
                                                  </a>")
                                                : 'No manpower attachment found.';
                                        })
                                        ->html(),
                                ]),
                        ]),
                    Step::make('Item Details')
                        ->description('Cost and manpower details retrieved from Profitability Analysis.')
                        ->schema([
                            Section::make('Source Documents (Manual Mode)')
                                ->description('Manual calculation files uploaded to Profitability Analysis.')
                                ->visible(function (Get $get) {
                                    $projectId = $get('project_id');
                                    if (! $projectId) {
                                        return false;
                                    }
                                    $pa = Project::find($projectId)?->profitabilityAnalysis;

                                    return $pa && (bool) $pa->is_manual_cost;
                                })
                                ->schema([
                                    TextEntry::make('operational_attachment_preview')
                                        ->label('Backup Costing Tools & Equipment')
                                        ->state(function (Get $get) {
                                            $projectId = $get('project_id');
                                            if (! $projectId) {
                                                return null;
                                            }
                                            $pa = Project::find($projectId)?->profitabilityAnalysis;
                                            if (! $pa) {
                                                return 'PA record not found.';
                                            }
                                            $media = $pa->getFirstMedia('operational_costing_backup');

                                            return $media
                                                ? new HtmlString("<a href='{$media->getTemporaryUrl(now()->addMinutes(60))}' target='_blank' class='text-primary-600 font-bold underline flex items-center gap-2'>
                                                    <svg class='w-4 h-4 inline-block' fill='none' stroke='currentColor' viewBox='0 0 24 24'><path stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4'></path></svg> 
                                                    Download Original Tools costing ({$media->file_name})
                                                  </a>")
                                                : 'No tools/equipment attachment found.';
                                        })
                                        ->html(),
                                ]),
                            Section::make('Project Costs')
                                ->description('Details of project cost components. Automatically retrieved from PA.')
                                ->visible(function (Get $get) {
                                    $projectId = $get('project_id');

                                    return (bool) Project::find($projectId)?->profitabilityAnalysis;
                                })
                                ->schema([
                                    TextEntry::make('items_details_preview')
                                        ->label('Operational Cost Details')
                                        ->state(function (Get $get) {
                                            $items = $get('content_config.items') ?? [];
                                            if (empty($items)) {
                                                return new HtmlString('<div class="rounded-lg bg-gray-50 p-4 text-sm text-gray-500 italic text-center border border-dashed border-gray-300">No operational items found. Please select a Project first.</div>');
                                            }

                                            $totalAmount = 0;
                                            $rows = collect($items)->map(function ($item) use (&$totalAmount) {
                                                $desc = $item['description'] ?? 'No Description';
                                                $uom = $item['uom'] ?? 'Unit';
                                                $qty = (float) ($item['quantity'] ?? 0);
                                                $price = (float) ($item['unit_price'] ?? 0);
                                                $total = (float) ($item['total_price'] ?? ($qty * $price));
                                                $totalAmount += $total;

                                                return "
                                                <tr class='hover:bg-gray-50/50 transition-colors'>
                                                    <td class='px-4 py-2 border-b border-gray-100 text-sm font-medium text-gray-900'>{$desc}</td>
                                                    <td class='px-4 py-2 border-b border-gray-100 text-sm text-gray-600'>{$uom}</td>
                                                    <td class='px-4 py-2 border-b border-gray-100 text-sm text-gray-600 text-right'>".number_format($qty)."</td>
                                                    <td class='px-4 py-2 border-b border-gray-100 text-sm text-gray-600 text-right'>".number_format($price, 0, ',', '.')."</td>
                                                    <td class='px-4 py-2 border-b border-gray-100 text-sm font-semibold text-gray-900 text-right'>".number_format($total, 0, ',', '.').'</td>
                                                </tr>';
                                            })->implode('');

                                            return new HtmlString("
                                                <div class='overflow-hidden rounded-xl border border-gray-200 shadow-sm'>
                                                    <table class='w-full text-left bg-white'>
                                                        <thead>
                                                            <tr class='bg-gray-50/80'>
                                                                <th class='px-4 py-3 text-xs font-bold text-gray-500 uppercase tracking-wider border-b border-gray-200'>Description</th>
                                                                <th class='px-4 py-3 text-xs font-bold text-gray-500 uppercase tracking-wider border-b border-gray-200'>UoM</th>
                                                                <th class='px-4 py-3 text-xs font-bold text-gray-500 uppercase tracking-wider text-right border-b border-gray-200'>Qty</th>
                                                                <th class='px-4 py-3 text-xs font-bold text-gray-500 uppercase tracking-wider text-right border-b border-gray-200'>Price</th>
                                                                <th class='px-4 py-3 text-xs font-bold text-gray-500 uppercase tracking-wider text-right border-b border-gray-200'>Total</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>{$rows}</tbody>
                                                        <tfoot class='bg-gray-50/30'>
                                                            <tr class='font-bold bg-blue-50/30'>
                                                                <td colspan='4' class='px-4 py-3 text-sm text-gray-900 uppercase'>Total Project Costs</td>
                                                                <td class='px-4 py-3 text-sm text-blue-700 text-right font-black'>IDR ".number_format($totalAmount, 0, ',', '.').'</td>
                                                            </tr>
                                                        </tfoot>
                                                    </table>
                                                </div>
                                            ');
                                        })
                                        ->html(),
                                ]),
                        ]),
                    Step::make('Financials & Terms')
                        ->description('Financial targets and payment terms.')
                        ->schema([
                            Grid::make(3)
                                ->schema([
                                    TextInput::make('amount')
                                        ->label('Grand Total / Month')
                                        ->placeholder('0.00')
                                        ->helperText('Nilai pendapatan kotor per bulan.')
                                        ->numeric()
                                        ->prefix('IDR')
                                        ->required(),
                                    TextInput::make('management_fee_percentage')
                                        ->label('Mgt. Fee')
                                        ->numeric()
                                        ->placeholder('10')
                                        ->suffix('%')
                                        ->default(10),
                                    TextInput::make('tax_percentage')
                                        ->label('Tax (VAT)')
                                        ->numeric()
                                        ->placeholder('11')
                                        ->suffix('%')
                                        ->default(11),
                                ]),
                            Section::make('Contractual Terms')
                                ->description('Administrative terms and personnel replacement SLA.')
                                ->schema([
                                    Grid::make(2)
                                        ->schema([
                                            Textarea::make('payment_terms')
                                                ->label('Terms of Payment')
                                                ->placeholder('e.g. Monthly, 30 Days TOP after invoice')
                                                ->helperText('Agreed payment system and scheduling.')
                                                ->rows(3),
                                            TextInput::make('probation_period')
                                                ->placeholder('e.g. 3 Months')
                                                ->default('3 Months'),
                                            TextInput::make('replacement_sla')
                                                ->label('Replacement SLA')
                                                ->placeholder('e.g. 3 Working Days')
                                                ->default('3 Working Days'),
                                            TextInput::make('reporting_schedule')
                                                ->placeholder('e.g. Every 25th of month')
                                                ->default('5th of each month'),
                                        ]),
                                ]),
                            Section::make('Official Document Upload')
                                ->description('Upload the reference draf and signed physical documents.')
                                ->schema([
                                    Grid::make(2)
                                        ->schema([
                                            SpatieMediaLibraryFileUpload::make('draft_so')
                                                ->collection('draft_so')
                                                ->label('Draft SO / Proposal Document')
                                                ->placeholder('Click or drag file here...')
                                                ->helperText('Internal review version (Max 10MB).'),

                                            SpatieMediaLibraryFileUpload::make('signed_so')
                                                ->collection('signed_so')
                                                ->label(fn (Get $get) => $get('type') === SalesOrderType::Internal->value
                                                    ? 'Approved Internal Memo / ST / PO (Scan)'
                                                    : 'Signed SO / SPK / PO (Scan)'
                                                )
                                                ->placeholder('Click or drag file here...')
                                                ->required(fn (Get $get) => $get('type') === SalesOrderType::Internal->value)
                                                ->helperText('Final legal document (Max 10MB).'),
                                        ]),
                                ]),
                        ]),
                ])
                    ->disabled(fn ($record) => $record && $record->status !== SalesOrderStatus::Draft)
                    ->columnSpanFull(),
            ]);
    }
}
