<?php

namespace Modules\CRM\Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Modules\CRM\Models\Customer;
use Modules\MasterData\Enums\LegalEntityType;
use Modules\MasterData\Models\RevenueSegment;
use Tests\TestCase;

class CreateOptionWorkflowTest extends TestCase
{
    use RefreshDatabase;

    protected User $user;

    protected function setUp(): void
    {
        parent::setUp();

        // Bypass permission check
        \Illuminate\Support\Facades\Gate::before(fn () => true);

        $this->user = User::factory()->create();
    }

    /** @test */
    public function it_can_instantiate_lead_form_schema(): void
    {
        $this->actingAs($this->user);

        $schema = \Modules\CRM\Filament\Clusters\CRM\Resources\Leads\Schemas\LeadForm::schema();
        $this->assertIsArray($schema);
    }

    /** @test */
    public function it_can_create_a_customer_model(): void
    {
        $this->actingAs($this->user);

        $customerData = [
            'name' => 'New Test Customer',
            'legal_entity_type' => LegalEntityType::PT->value,
            'status' => \Modules\MasterData\Enums\ActiveStatus::Active->value,
        ];

        $customer = Customer::create($customerData);
        $this->assertDatabaseHas(Customer::class, ['name' => 'New Test Customer']);
        $this->assertNotNull($customer->code, 'Customer code should be auto-generated by observer.');
    }

    /** @test */
    public function it_can_create_a_revenue_segment_via_the_lead_creation_modal(): void
    {
        $this->actingAs($this->user);

        $segmentData = [
            'name' => 'New Revenue Segment',
            'code' => 'RS001',
            'is_active' => true,
        ];

        $segment = RevenueSegment::create($segmentData);
        $this->assertDatabaseHas(RevenueSegment::class, ['name' => 'New Revenue Segment']);
    }
}
