<?php

namespace Modules\MasterData\Database\Seeders;

use Illuminate\Database\Seeder;

class MasterCodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Work Schemes
        $workSchemes = [
            ['code' => '01', 'name' => 'TAD/Headcount'],
            ['code' => '02', 'name' => 'Borongan'],
            ['code' => '03', 'name' => 'Mitra'],
            ['code' => '04', 'name' => 'Head Hunter'],
            ['code' => 'OT', 'name' => 'Others'],
        ];
        foreach ($workSchemes as $data) {
            \Modules\MasterData\Models\WorkScheme::updateOrCreate(['code' => $data['code']], $data);
        }

        // Product Clusters
        $productClusters = [
            ['code' => 'BCA', 'name' => 'Product Cluster Beyond Care'],
            ['code' => 'BCL', 'name' => 'Product Cluster Beyond Clean'],
            ['code' => 'BFR', 'name' => 'Product Cluster Beyond Fresh'],
            ['code' => 'BSE', 'name' => 'Product Cluster Beyond Secure'],
            ['code' => 'BSK', 'name' => 'Product Cluster Beyond Sky'],
            ['code' => 'SFA', 'name' => 'Product Cluster Smart Facilities'],
            ['code' => 'GTR', 'name' => 'Product Cluster GDPS Terrace'],
            ['code' => 'MGT', 'name' => 'Product Cluster GDPS Other'],
            ['code' => 'OTS', 'name' => 'Product Cluster Others_'],
        ];
        foreach ($productClusters as $data) {
            \Modules\MasterData\Models\ProductCluster::updateOrCreate(['code' => $data['code']], $data);
        }

        // Taxes
        $taxes = [
            ['code' => 'P1', 'name' => 'PPh 21 ditanggung perusahaan/customer'],
            ['code' => 'P2', 'name' => 'PPh 21 ditanggung karyawan'],
            ['code' => 'P3', 'name' => 'PPh 21 Final - perusahaan/customer'],
            ['code' => 'OT', 'name' => 'Others'],
        ];
        foreach ($taxes as $data) {
            \Modules\MasterData\Models\Tax::updateOrCreate(['code' => $data['code']], $data);
        }

        // Companies
        // Companies
        $companies = [
            ['code' => 'ABB', 'name' => 'PT Anugerah Bangun Bersama'],
            ['code' => 'ACE', 'name' => 'PT Anugrah Cita Era Food'],
            ['code' => 'ACS', 'name' => 'PT Aerofood Indonesia'],
            ['code' => 'AGI', 'name' => 'PT Aero Globe Indonesia'],
            ['code' => 'AIC', 'name' => 'PT Aice Indonesia'],
            ['code' => 'ASA', 'name' => 'PT Adhitama Sejahtera Alami'],
            ['code' => 'ASY', 'name' => 'PT Aero System Indonesia'],
            ['code' => 'AWS', 'name' => 'PT Aerowisata'],
            ['code' => 'BAT', 'name' => 'PT British American Tobacco'],
            ['code' => 'BHI', 'name' => 'PT Baker Hughes Indonesia'],
            ['code' => 'BMC', 'name' => 'PT Braja Mukti Cakra'],
            ['code' => 'BPR', 'name' => 'PT Bentoel Prima'],
            ['code' => 'BTO', 'name' => 'PT Bintang Toedjoe'],
            ['code' => 'CKT', 'name' => 'PT Ciptaloka Karsa Teknologi'],
            ['code' => 'CSF', 'name' => 'PT Caturnusa Sejahtera Finance'],
            ['code' => 'DLA', 'name' => 'PT Deltomed Laboratories'],
            ['code' => 'DPP', 'name' => 'PT Dutagaruda Piranti Prima'],
            ['code' => 'DSJ', 'name' => 'PT Distribusi Sentra Jaya'],
            ['code' => 'GFO', 'name' => 'Gagafood'],
            ['code' => 'GGC', 'name' => 'GDPS Goldcare'],
            ['code' => 'GIA', 'name' => 'PT Garuda Indonesia'],
            ['code' => 'GMF', 'name' => 'PT GMF Aeroasia, Tbk.'],
            ['code' => 'GOT', 'name' => 'GDPS Other'],
            ['code' => 'GPS', 'name' => 'Gita Prima Selaras'],
            ['code' => 'GRP', 'name' => 'PT Gunung Raja Paksi'],
            ['code' => 'GTI', 'name' => 'PT Grab Teknologi Indonesia'],
            ['code' => 'GDP', 'name' => 'PT GDPS'],
            ['code' => 'IKN', 'name' => 'PT Inklusi Keuangan Nusantara'],
            ['code' => 'JAE', 'name' => 'PT Jas Aero Engineering Services'],
            ['code' => 'JAS', 'name' => 'PT Jasa Angkasa Semesta'],
            ['code' => 'JCI', 'name' => 'PT Japfa Comfeed Indonesia, Tbk.'],
            ['code' => 'JTA', 'name' => 'PT Jakarana Tama'],
            ['code' => 'KOP', 'name' => 'PT Kopnuspos'],
            ['code' => 'KPH', 'name' => 'PT Kreanova Pharmaret'],
            ['code' => 'KTI', 'name' => 'PT Kudo Teknologi Indonesia'],
            ['code' => 'LLI', 'name' => 'PT Linfox Logistics Indonesia'],
            ['code' => 'MNN', 'name' => 'PT Maha Nagari Nusantara'],
            ['code' => 'MNP', 'name' => 'PT Madusari Nusaperdana'],
            ['code' => 'MSA', 'name' => 'PT Mitra Semen Asia'],
            ['code' => 'PFI', 'name' => 'PT Pet Food Indoprima'],
            ['code' => 'PNT', 'name' => 'PT Panca Nusa Travelindo'],
            ['code' => 'QGA', 'name' => 'PT Citilink Indonesia'],
            ['code' => 'RIN', 'name' => 'PT Rhipe International'],
            ['code' => 'SAN', 'name' => 'PT Sanad A Mubadala Company'],
            ['code' => 'SGF', 'name' => 'PT So Good Food Manufacturing'],
            ['code' => 'SMU', 'name' => 'PT Sayap Mas Utama'],
            ['code' => 'STE', 'name' => 'PT Smartfren Telecom Tbk'],
            ['code' => 'SUI', 'name' => 'PT Sepeda Untuk Indonesia'],
            ['code' => 'TIN', 'name' => 'PT Traveloka Indonesia'],
            ['code' => 'TTR', 'name' => 'PT Trinusa Travelindo'],
            ['code' => 'UID', 'name' => 'Universitas Indonesia'],
            ['code' => 'VKA', 'name' => 'PT Virama Karya'],
            ['code' => 'YMA', 'name' => 'Yayasan Marala'],
            ['code' => 'ZIL', 'name' => 'Zespri International Limited'],
            ['code' => 'MDI', 'name' => 'PT Mengniu Dairy Indonesia (Yoyic)'],
            ['code' => 'FJA', 'name' => 'Fiji Airways'],
            ['code' => 'SSI', 'name' => 'PT SGMW Sales Indonesia'],
            ['code' => 'SMI', 'name' => 'PT SGMW Motor Indonesia'],
            ['code' => 'KCC', 'name' => 'PT Kereta Cepat Indonesia China (KCIC)'],
            ['code' => 'CKI', 'name' => 'PT Krayon Konsultan Indo'],
            ['code' => 'RSH', 'name' => 'RS Haji'],
            ['code' => 'SZI', 'name' => 'PT Shenglu Zhangmei International'],
            ['code' => 'JJN', 'name' => 'PT Jalan-Jalan Nusantara'],
            ['code' => 'SIM', 'name' => 'PT Sentosa Indo Mulya'],
            ['code' => 'AUF', 'name' => 'PT Andalan Utama Foodindo'],
            ['code' => 'PRS', 'name' => 'Perumnas'],
            ['code' => 'STN', 'name' => 'PT Sabre Travel Network Indonesia'],
            ['code' => 'ZIN', 'name' => 'PT Zalora Indonesia'],
            ['code' => 'BDU', 'name' => 'PT Bentoel Distributor Utama'],
            ['code' => 'SII', 'name' => 'PT SAIC Internasional Indonesia'],
            ['code' => 'AJI', 'name' => 'PT AICE Ice Cream Jatim Industry'],
            ['code' => 'KBN', 'name' => 'Kementrian BUMN'],
            ['code' => 'RXI', 'name' => 'PT RUI XUE INTERNATIONAL'],
            ['code' => 'FMP', 'name' => 'PT Fashion Marketplace'],
            ['code' => 'GPA', 'name' => 'PT Gapura Angkasa'],
            ['code' => 'AFI', 'name' => 'PT Alpen Food Industry'],
            ['code' => 'JPC', 'name' => 'Jakarta Praise Community Church'],
            ['code' => 'KII', 'name' => 'PT Kerajaan Ice Indonesia'],
            ['code' => 'GEM', 'name' => 'PT. GERBANG EDUKASI MAKMUR'],
            ['code' => 'PLI', 'name' => 'PT Pos Logistik Indonesia'],
            ['code' => 'MTE', 'name' => 'PT MENTARI TIMUR EKSPEDISI'],
            ['code' => 'PAJ', 'name' => 'CV Pratama Artha Jaya'],
            ['code' => 'AJC', 'name' => 'PT Aerojasa Cargo'],
            ['code' => 'AIM', 'name' => 'PT Andalas Indah Makmur'],
            ['code' => 'KNA', 'name' => 'PT Kalista Nusa Armada'],
            ['code' => 'KSH', 'name' => 'PT Kalista Soter Hastia'],
            ['code' => 'BEC', 'name' => 'PT Bumilangit Entertainment Corpora'],
            ['code' => 'PIP', 'name' => 'PLN Indonesia Power'],
            ['code' => 'MBS', 'name' => 'PT Mega Boga Sagara'],
            ['code' => 'SUB', 'name' => 'PT Senang Untuk Berbagi'],
            ['code' => 'KBI', 'name' => 'PT Kalista Biru Nusantara'],
            ['code' => 'YIC', 'name' => 'CV Yammi Ice Cream'],
            ['code' => 'PFT', 'name' => 'PT Profit Foods Tranding'],
            ['code' => 'SEI', 'name' => 'PT Sicepat Ekspres Indonesia'],
            ['code' => 'HBI', 'name' => 'PT Hiboo Baby Indonesia'],
            ['code' => 'PAL', 'name' => 'PNG Air Limited'],
            ['code' => 'AEC', 'name' => 'PT ACMIC ELECTRONIC'],
            ['code' => 'BFI', 'name' => 'PT Belfood Indonesia'],
            ['code' => 'GFP', 'name' => 'PT GRIFF PRIMA ABADI'],
            ['code' => 'KLI', 'name' => 'PT KOHLER INDONESIA'],
            ['code' => 'KMI', 'name' => 'PT KOHLER MANUFACTURING INDONESIA'],
            ['code' => 'APR', 'name' => 'PT Aneka Petroindo Raya'],
            ['code' => 'GMI', 'name' => 'PT Gading Murni'],
            ['code' => 'CBI', 'name' => 'PT. CEMERLANG BERJAYA INDONESIA'],
            ['code' => 'AJN', 'name' => 'PT Agrinas Jaladri Nusantara'],
            ['code' => 'SSM', 'name' => 'PT Strada Satya Makmur'],
            ['code' => 'TAP', 'name' => 'TALENT ANGELS PTE LTD,'],
            ['code' => 'ETA', 'name' => 'PT Ekspres Transportasi Antarbenua'],
            ['code' => 'WAD', 'name' => 'PT Wira Adirajasa Dirgantara'],
            ['code' => 'ATF', 'name' => 'PT ARTHA UTAMA FOODINDO'],
            ['code' => 'KMG', 'name' => 'Keumseong LLC'],
            ['code' => 'GDPS', 'name' => 'PT Garuda Daya Pratama Sejahtera'],
            ['code' => 'GAP', 'name' => 'PT Gapura Angkasa'],
        ];

        foreach ($companies as $data) {
            $fullName = $data['name'];
            $legalEntityType = null;
            $cleanName = $fullName;

            $types = ['PT', 'CV', 'UD', 'Yayasan', 'Koperasi', 'Firma'];
            foreach ($types as $type) {
                if (str_starts_with($fullName, $type.' ')) {
                    $legalEntityType = $type;
                    $cleanName = trim(substr($fullName, strlen($type)));
                    break;
                }
            }

            \Modules\MasterData\Models\Client::updateOrCreate(
                ['code' => $data['code']],
                [
                    'name' => $cleanName,
                    'legal_entity_type' => $legalEntityType,
                    'status' => 'active',
                ]
            );
        }

        // Project Areas
        $areas = [
            ['code' => null, 'name' => 'Kalimantan Timur/Samarinda'],
            ['code' => 'AMQ', 'name' => 'Maluku'],
            ['code' => 'BDG', 'name' => 'Bandung Barat'],
            ['code' => 'BDJ', 'name' => 'Kalimantan Selatan/Banjar'],
            ['code' => 'KBD', 'name' => 'Kab. Bandung'],
            ['code' => 'BEK', 'name' => 'Bekasi'],
            ['code' => 'BJO', 'name' => 'Bojonegoro'],
            ['code' => 'BKL', 'name' => 'Bangkalan'],
            ['code' => 'BLO', 'name' => 'Blora'],
            ['code' => 'BNR', 'name' => 'Banjarnegara'],
            ['code' => 'BNY', 'name' => 'Banyumas'],
            ['code' => 'BOG', 'name' => 'Bogor'],
            ['code' => 'BPN', 'name' => 'Balikpapan'],
            ['code' => 'BRE', 'name' => 'Brebes'],
            ['code' => 'BTG', 'name' => 'Batang'],
            ['code' => 'BTH', 'name' => 'Batam'],
            ['code' => 'BTJ', 'name' => 'Aceh'],
            ['code' => 'BTL', 'name' => 'Blitar'],
            ['code' => 'BWI', 'name' => 'Banyuwangi'],
            ['code' => 'BYL', 'name' => 'Boyolali'],
            ['code' => 'CGK', 'name' => 'Cengkareng'],
            ['code' => 'CIA', 'name' => 'Cianjur, Sukabumi'],
            ['code' => 'CKR', 'name' => 'Cikarang'],
            ['code' => 'CLA', 'name' => 'Cilacap'],
            ['code' => 'CRB', 'name' => 'Cirebon'],
            ['code' => 'DEM', 'name' => 'Demak'],
            ['code' => 'DEP', 'name' => 'Depok'],
            ['code' => 'DJB', 'name' => 'Jambi'],
            ['code' => 'DJJ', 'name' => 'Papua'],
            ['code' => 'DOM', 'name' => 'Papua Barat'],
            ['code' => 'DPS', 'name' => 'Denpasar'],
            ['code' => 'FKS', 'name' => 'Bengkulu'],
            ['code' => 'GAT', 'name' => 'Garut'],
            ['code' => 'GND', 'name' => 'Gorontalo'],
            ['code' => 'GRB', 'name' => 'Grobogan'],
            ['code' => 'GRG', 'name' => 'Grogol'],
            ['code' => 'GRS', 'name' => 'Gresik'],
            ['code' => 'GUM', 'name' => 'Maluku Utara'],
            ['code' => 'JKR', 'name' => 'Jabodetabekar'],
            ['code' => 'HLP', 'name' => 'Halim Perdana Kusuma'],
            ['code' => 'HOF', 'name' => 'Head Office'],
            ['code' => 'IDN', 'name' => 'Indramayu'],
            ['code' => 'JBA', 'name' => 'Jakarta Barat'],
            ['code' => 'JBG', 'name' => 'Jombang'],
            ['code' => 'JBR', 'name' => 'Jember'],
            ['code' => 'JPR', 'name' => 'Jepara'],
            ['code' => 'JSE', 'name' => 'Jakarta Selatan'],
            ['code' => 'JTI', 'name' => 'Jakarta Timur'],
            ['code' => 'JUT', 'name' => 'Jakarta Utara'],
            ['code' => 'KBM', 'name' => 'Kebumen'],
            ['code' => 'KDI', 'name' => 'Sulawesi Tenggara/Kendari'],
            ['code' => 'KDL', 'name' => 'Kendal'],
            ['code' => 'KDR', 'name' => 'Kediri'],
            ['code' => 'KDS', 'name' => 'Kudus'],
            ['code' => 'KLT', 'name' => 'Klaten'],
            ['code' => 'KNG', 'name' => 'Kuningan'],
            ['code' => 'KNO', 'name' => 'Kualanamu'],
            ['code' => 'KRW', 'name' => 'Karawang'],
            ['code' => 'KRY', 'name' => 'Karanganyar'],
            ['code' => 'LMJ', 'name' => 'Lumajang'],
            ['code' => 'LMN', 'name' => 'Lamongan'],
            ['code' => 'LOP', 'name' => 'Lombok'],
            ['code' => 'MAJ', 'name' => 'Majalengka'],
            ['code' => 'MDC', 'name' => 'Sulawesi Utara/Manado'],
            ['code' => 'MDN', 'name' => 'Madiun'],
            ['code' => 'MGL', 'name' => 'Magelang'],
            ['code' => 'MJK', 'name' => 'Mojokerto'],
            ['code' => 'MJU', 'name' => 'Sulawesi Tengah'],
            ['code' => 'MLG', 'name' => 'Malang'],
            ['code' => 'MTN', 'name' => 'Magetan'],
            ['code' => 'NGJ', 'name' => 'Nganjuk'],
            ['code' => 'NGW', 'name' => 'Ngawi'],
            ['code' => 'PAR', 'name' => 'Pare-pare'],
            ['code' => 'PAS', 'name' => 'Pasuruan'],
            ['code' => 'PAT', 'name' => 'Pati'],
            ['code' => 'PBL', 'name' => 'Probolinggo'],
            ['code' => 'PCT', 'name' => 'Pacitan'],
            ['code' => 'PDG', 'name' => 'Sumatera Barat'],
            ['code' => 'SUM', 'name' => 'Sumatera'],
            ['code' => 'PKL', 'name' => 'Pekalongan'],
            ['code' => 'PKU', 'name' => 'Riau/Pekanbaru, Duri/Taluk Kuantan'],
            ['code' => 'PKY', 'name' => 'Kalimantan Tengah/Palangkaraya'],
            ['code' => 'PLG', 'name' => 'Purbalingga'],
            ['code' => 'PLM', 'name' => 'Palembang, Prabumulih'],
            ['code' => 'PMK', 'name' => 'Pamekasan'],
            ['code' => 'PML', 'name' => 'Pemalang'],
            ['code' => 'PML', 'name' => 'Pemalang'],
            ['code' => 'PND', 'name' => 'Pangandaran'],
            ['code' => 'PNK', 'name' => 'Kalimantan Barat/Pontianak'],
            ['code' => 'PON', 'name' => 'Ponorogo'],
            ['code' => 'PRW', 'name' => 'Purworejo'],
            ['code' => 'PWT', 'name' => 'Purwakarta'],
            ['code' => 'RBM', 'name' => 'Rembang'],
            ['code' => 'RE1', 'name' => 'Region 1'],
            ['code' => 'RE2', 'name' => 'Region 2'],
            ['code' => 'RE3', 'name' => 'Region 3'],
            ['code' => 'RE4', 'name' => 'Region 4'],
            ['code' => 'RE5', 'name' => 'Region 5'],
            ['code' => 'SBG', 'name' => 'Subang'],
            ['code' => 'SID', 'name' => 'Sidoarjo'],
            ['code' => 'SIT', 'name' => 'Situbondo'],
            ['code' => 'SMD', 'name' => 'Sumedang'],
            ['code' => 'SMN', 'name' => 'Sumenep'],
            ['code' => 'SMP', 'name' => 'Sampang'],
            ['code' => 'SOC', 'name' => 'Solo'],
            ['code' => 'SRA', 'name' => 'Sragen'],
            ['code' => 'SRG', 'name' => 'Semarang'],
            ['code' => 'SUB', 'name' => 'Surabaya'],
            ['code' => 'TAS', 'name' => 'Tasikmalaya'],
            ['code' => 'TGG', 'name' => 'Sulawesi Barat'],
            ['code' => 'JTM', 'name' => 'Jawa Timur'],
            ['code' => 'TGL', 'name' => 'Tegal'],
            ['code' => 'TJQ', 'name' => 'Bangka Belitung/ Tanjung Pandan'],
            ['code' => 'TKG', 'name' => 'Lampung'],
            ['code' => 'TMG', 'name' => 'Temanggung'],
            ['code' => 'TNJ', 'name' => 'Tanjung Pinang, Kepri'],
            ['code' => 'TRK', 'name' => 'Kalimantan Utara/Tarakan'],
            ['code' => 'UPG', 'name' => 'Sulawesi Selatan/Ujung Pandang'],
            ['code' => 'WNG', 'name' => 'Wonogiri'],
            ['code' => 'WSO', 'name' => 'Wonosobo'],
            ['code' => 'YIA', 'name' => 'Yogyakarta'],
            ['code' => 'ZOD', 'name' => 'Gudang Zoodia'],
            ['code' => 'ALL', 'name' => 'All Area'],
            ['code' => 'CGO', 'name' => 'Cargo Warehouse'],
            ['code' => 'TE3', 'name' => 'Terminal 3'],
            ['code' => 'TE1', 'name' => 'Terminal 1'],
            ['code' => 'TE2', 'name' => 'Terminal 2'],
            ['code' => 'GIT', 'name' => 'GITC'],
            ['code' => 'KSI', 'name' => 'Kebon Sirih'],
            ['code' => 'GSA', 'name' => 'Gunung Sahari'],
            ['code' => 'KMO', 'name' => 'Kemayoran'],
            ['code' => 'BIN', 'name' => 'Bintaro'],
            ['code' => 'CIK', 'name' => 'Cikokol'],
            ['code' => 'TNG', 'name' => 'Tangerang'],
            ['code' => 'JPU', 'name' => 'Jakarta Pusat'],
            ['code' => 'BOF', 'name' => 'Back of Factory'],
            ['code' => 'WDC', 'name' => 'West DC'],
            ['code' => 'MPA', 'name' => 'Menara Palma'],
            ['code' => 'SIL', 'name' => 'Siliwangi'],
            ['code' => 'TBB', 'name' => 'TBB'],
            ['code' => 'JTH', 'name' => 'Jawa Tengah'],
            ['code' => 'TGS', 'name' => 'Tangerang Selatan'],
            ['code' => 'GSK', 'name' => 'Gersik'],
            ['code' => 'JDB', 'name' => 'Jabodetabek'],
            ['code' => 'BBR', 'name' => 'Bintaro,Bogor'],
            ['code' => 'SLP', 'name' => 'Slipi'],
            ['code' => 'JBT', 'name' => 'Jawa Barat'],
            ['code' => 'TBT', 'name' => 'Tebet'],
            ['code' => 'KSL', 'name' => 'Kalimantan,Sulawesi'],
            ['code' => 'BDO', 'name' => 'Bandung'],
            ['code' => 'JKT', 'name' => 'Jakarta'],
            ['code' => 'SGT', 'name' => 'Sumbagut'],
            ['code' => 'MED', 'name' => 'Medan'],
            ['code' => 'IKN', 'name' => 'Ibu Kota Nusantara'],
            ['code' => 'CKD', 'name' => 'Cikande'],
            ['code' => 'FJI', 'name' => 'Fiji'],
            ['code' => 'TLL', 'name' => 'Tegalluar'],
            ['code' => 'BNJ', 'name' => 'Binjai'],
            ['code' => 'SIN', 'name' => 'Singapura'],
            ['code' => 'ROK', 'name' => 'Korea Selatan'],
        ];
        foreach ($areas as $data) {
            \Modules\MasterData\Models\ProjectArea::updateOrCreate(['name' => $data['name']], $data);
        }
    }
}
