<?php

namespace Modules\Finance\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Finance\Models\ChartOfAccount;

class SapChartOfAccountSeeder extends Seeder
{
    /**
     * Cache for created group records to avoid redundant queries.
     */
    protected array $cache = [];

    public function run(): void
    {
        $groupMapping = [
            'Cash and Cash Equivalents' => '1100',
            'AR Trade Related Parties' => '1200',
            'AR Trade Third Parties' => '1300',
            'Accrued Revenue Related Parties' => '1400',
            'Accrued Revenue Third Parties' => '1500',
            'Advance Payment' => '1600',
            'Prepaid Taxes' => '1700',
            'Prepaid Expenses' => '1800',
            'Deferred Tax Assets' => '1900',
            'Security Deposit' => '1910',
            'Property and Equipment' => '1920',
            'AP Trade Related Parties' => '2100',
            'AP Trade Third Parties' => '2200',
            'Taxes Payable' => '2300',
            'Accrued Expenses' => '2400',
            'Accrued Expenses Related Parties' => '2410',
            'Other Account Payable' => '2500',
            'Capital Stock' => '2600',
            'RE Unappropriated' => '2700',
            'Employee Benefits Obligation' => '2800',
            'Other comprehensive income' => '2810',
            'Current Lease Liability' => '2900',
            'Non Current Lease Liability' => '2910',
            'Dividend' => '2920',
            'Revenue from GA Group' => '3100',
            'Revenue from Third Parties' => '3200',
            'Revenue from GMF' => '3300',
            'Manpower Expenses' => '4100',
            'Staff Expenses' => '4200',
            'Operating Expenses' => '4300',
            'Depreciation, Amortization, and Impairment' => '4400',
            'Other Operating Expenses' => '4500',
            'TAX EXPENSE' => '5100',
            'Finance Charges' => '5200',
            'Finance Income' => '5300',
            'Right Of Use Asset' => '9100',
        ];

        $data = [
            ['10000064', 'Balance Sheet', 'PETTY CASH GDPS-IDR', 'Cash and Cash Equivalents'],
            ['10002310', 'Balance Sheet', 'BANK MANDIRI-IDR', 'Cash and Cash Equivalents'],
            ['10002314', 'Balance Sheet', 'BANK MANDIRI-TABUNGAN BISNIS', 'Cash and Cash Equivalents'],
            ['10002404', 'Balance Sheet', 'BANK BNI GIRO-IDR', 'Cash and Cash Equivalents'],
            ['10017200', 'Balance Sheet', 'ACCOUNT RECEIVABLE-TP-DOMESTIC', 'AR Trade Third Parties'],
            ['10018905', 'Balance Sheet', 'ACCRUED REVENUE THIRD PARTIES', 'Accrued Revenue Third Parties'],
            ['10040100', 'Balance Sheet', 'ADVANCE PAYMENT-THIRD PARTY-DOM', 'Advance Payment'],
            ['10055200', 'Balance Sheet', 'PREPAID WITHOLDING TAX-ARTICLE-22', 'Prepaid Taxes'],
            ['10055300', 'Balance Sheet', 'PREPAID WITHOLDING TAX-ARTICLE-23', 'Prepaid Taxes'],
            ['10055700', 'Balance Sheet', 'PREPAID-VALUE ADDED TAX-IN', 'Taxes Payable'],
            ['10060026', 'Balance Sheet', 'FURNITURE-PROD', 'Property and Equipment'],
            ['10060036', 'Balance Sheet', 'HARDWARE-PROD', 'Property and Equipment'],
            ['10060052', 'Balance Sheet', 'TOOLS-PROD', 'Property and Equipment'],
            ['10060054', 'Balance Sheet', 'VEHICLE-PROD', 'Property and Equipment'],
            ['10065016', 'Balance Sheet', 'ACCUMULATED DEPR-FURNITURE-PROD', 'Property and Equipment'],
            ['10065022', 'Balance Sheet', 'ACCUMULATED DEPR-HARDWARE-PROD', 'Property and Equipment'],
            ['10065034', 'Balance Sheet', 'ACCUMULATED DEPR-TOOLS-PROD', 'Property and Equipment'],
            ['10065036', 'Balance Sheet', 'ACCUMULATED DEPR-VEHICLE-PROD', 'Property and Equipment'],
            ['11002500', 'Balance Sheet', 'GDPS BRI GIRO-IDR-144201000003304', 'Cash and Cash Equivalents'],
            ['11010012', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA  HODI', 'AR Trade Related Parties'],
            ['11010014', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA  HOCH', 'AR Trade Related Parties'],
            ['11010066', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA DJB0', 'AR Trade Related Parties'],
            ['11010076', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA MES0', 'AR Trade Related Parties'],
            ['11010078', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA PDG0', 'AR Trade Related Parties'],
            ['11010082', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA PKU0', 'AR Trade Related Parties'],
            ['11010084', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA PLM0', 'AR Trade Related Parties'],
            ['11010088', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA TKG0', 'AR Trade Related Parties'],
            ['11010090', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA TNJ0', 'AR Trade Related Parties'],
            ['11010188', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA DPS0', 'AR Trade Related Parties'],
            ['11010192', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA KOE0', 'AR Trade Related Parties'],
            ['11010194', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA LOP0', 'AR Trade Related Parties'],
            ['11010196', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA MLG0', 'AR Trade Related Parties'],
            ['11010198', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA SOC0', 'AR Trade Related Parties'],
            ['11010202', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA SUB0', 'AR Trade Related Parties'],
            ['11010248', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA BIK0', 'AR Trade Related Parties'],
            ['11010250', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA BPN0', 'AR Trade Related Parties'],
            ['11010254', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA GTO0', 'AR Trade Related Parties'],
            ['11010256', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA KDI0', 'AR Trade Related Parties'],
            ['11010260', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA MDC0', 'AR Trade Related Parties'],
            ['11010270', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA PKY0', 'AR Trade Related Parties'],
            ['11010272', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA PLW0', 'AR Trade Related Parties'],
            ['11010276', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA SOQ0', 'AR Trade Related Parties'],
            ['11010280', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA TIM0', 'AR Trade Related Parties'],
            ['11010284', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA TTE0', 'AR Trade Related Parties'],
            ['11010286', 'Balance Sheet', 'ACCOUNT RECEIVABLE - GA UPG0', 'AR Trade Related Parties'],
            ['11012060', 'Balance Sheet', 'ACCOUNT RECEIVABLE-CT00', 'AR Trade Related Parties'],
            ['11014000', 'Balance Sheet', 'ACCOUNT RECEIVABLE-AC00', 'AR Trade Related Parties'],
            ['11014002', 'Balance Sheet', 'ACCOUNT RECEIVABLE-AC01', 'AR Trade Related Parties'],
            ['11018000', 'Balance Sheet', 'ACCRUED REVENUE-GMF', 'Accrued Revenue Related Parties'],
            ['11018006', 'Balance Sheet', 'ACCRUED REVENUE- GA HOGF', 'Accrued Revenue Related Parties'],
            ['11018032', 'Balance Sheet', 'ACCRUED REVENUE-CITILINK', 'Accrued Revenue Related Parties'],
            ['11018060', 'Balance Sheet', 'ACCRUED REVENUE- GA BKS0', 'Accrued Revenue Related Parties'],
            ['11018062', 'Balance Sheet', 'ACCRUED REVENUE- GA BTH0', 'Accrued Revenue Related Parties'],
            ['11018064', 'Balance Sheet', 'ACCRUED REVENUE- GA BTJ0', 'Accrued Revenue Related Parties'],
            ['11018066', 'Balance Sheet', 'ACCRUED REVENUE- GA DJB0', 'Accrued Revenue Related Parties'],
            ['11018074', 'Balance Sheet', 'ACCRUED REVENUE- GA KNO0', 'Accrued Revenue Related Parties'],
            ['11018078', 'Balance Sheet', 'ACCRUED REVENUE- GA PDG0', 'Accrued Revenue Related Parties'],
            ['11018080', 'Balance Sheet', 'ACCRUED REVENUE- GA PGK0', 'Accrued Revenue Related Parties'],
            ['11018082', 'Balance Sheet', 'ACCRUED REVENUE- GA PKU0', 'Accrued Revenue Related Parties'],
            ['11018084', 'Balance Sheet', 'ACCRUED REVENUE- GA PLM0', 'Accrued Revenue Related Parties'],
            ['11018088', 'Balance Sheet', 'ACCRUED REVENUE- GA TGK0', 'Accrued Revenue Related Parties'],
            ['11018090', 'Balance Sheet', 'ACCRUED REVENUE- GA TNJ0', 'Accrued Revenue Related Parties'],
            ['11018100', 'Balance Sheet', 'ACCRUE REVENUE HODI', 'Accrued Revenue Related Parties'],
            ['11018124', 'Balance Sheet', 'ACCRUED REVENUE- GA CGK0', 'Accrued Revenue Related Parties'],
            ['11018188', 'Balance Sheet', 'ACCRUED REVENUE- GA DPS0', 'Accrued Revenue Related Parties'],
            ['11018190', 'Balance Sheet', 'ACCRUED REVENUE- GA JOG0', 'Accrued Revenue Related Parties'],
            ['11018192', 'Balance Sheet', 'ACCRUED REVENUE- GA KOE0', 'Accrued Revenue Related Parties'],
            ['11018194', 'Balance Sheet', 'ACCRUED REVENUE- GA LOP0', 'Accrued Revenue Related Parties'],
            ['11018198', 'Balance Sheet', 'ACCRUED REVENUE- GA SOC0', 'Accrued Revenue Related Parties'],
            ['11018200', 'Balance Sheet', 'ACCRUED REVENUE- GA SRG0', 'Accrued Revenue Related Parties'],
            ['11018202', 'Balance Sheet', 'ACCRUED REVENUE- GA SUB0', 'Accrued Revenue Related Parties'],
            ['11018242', 'Balance Sheet', 'ACCRUED REVENUE- GA AMQ0', 'Accrued Revenue Related Parties'],
            ['11018244', 'Balance Sheet', 'ACCRUED REVENUE- GA BDJ0', 'Accrued Revenue Related Parties'],
            ['11018248', 'Balance Sheet', 'ACCRUED REVENUE- GA BIK0', 'Accrued Revenue Related Parties'],
            ['11018250', 'Balance Sheet', 'ACCRUED REVENUE- GA BPN0', 'Accrued Revenue Related Parties'],
            ['11018252', 'Balance Sheet', 'ACCRUED REVENUE- GA DJJ0', 'Accrued Revenue Related Parties'],
            ['11018254', 'Balance Sheet', 'ACCRUED REVENUE- GA GTO0', 'Accrued Revenue Related Parties'],
            ['11018256', 'Balance Sheet', 'ACCRUED REVENUE- GA KDI0', 'Accrued Revenue Related Parties'],
            ['11018260', 'Balance Sheet', 'ACCRUED REVENUE- GA MDC0', 'Accrued Revenue Related Parties'],
            ['11018264', 'Balance Sheet', 'ACCRUED REVENUE- GA MKQ0', 'Accrued Revenue Related Parties'],
            ['11018270', 'Balance Sheet', 'ACCRUED REVENUE- GA PKY0', 'Accrued Revenue Related Parties'],
            ['11018272', 'Balance Sheet', 'ACCRUED REVENUE- GA PLW0', 'Accrued Revenue Related Parties'],
            ['11018274', 'Balance Sheet', 'ACCRUED REVENUE- GA PNK0', 'Accrued Revenue Related Parties'],
            ['11018276', 'Balance Sheet', 'ACCRUED REVENUE- GA SOQ0', 'Accrued Revenue Related Parties'],
            ['11018280', 'Balance Sheet', 'ACCRUED REVENUE- GA TIM0', 'Accrued Revenue Related Parties'],
            ['11018284', 'Balance Sheet', 'ACCRUED REVENUE- GA TTE0', 'Accrued Revenue Related Parties'],
            ['11018286', 'Balance Sheet', 'ACCRUED REVENUE- GA UPG0', 'Accrued Revenue Related Parties'],
            ['11018500', 'Balance Sheet', 'ACCRUED REVENUE-AC00', 'Accrued Revenue Related Parties'],
            ['11018502', 'Balance Sheet', 'ACCRUED REVENUE-AC01', 'Accrued Revenue Related Parties'],
            ['11019050', 'Balance Sheet', 'ACCOUNT RECEIVABLE-GMF', 'AR Trade Related Parties'],
            ['11057000', 'Balance Sheet', 'DEFERED TAX ASSET', 'Deferred Tax Assets'],
            ['11060002', 'Balance Sheet', 'BUILDING', 'Property and Equipment'],
            ['11060014', 'Balance Sheet', 'SOFTWARE', 'Property and Equipment'],
            ['11065002', 'Balance Sheet', 'ACCUMULATED DEPR-BUILDING-PROD', 'Property and Equipment'],
            ['11065014', 'Balance Sheet', 'ACCUMULATED DEPR-SOFTWARE-PROD', 'Property and Equipment'],
            ['20003100', 'Balance Sheet', 'WITHOLDING TAX PAYABLE ARTICLE 21', 'Taxes Payable'],
            ['20003300', 'Balance Sheet', 'WITHOLDING TAX PAYABLE ARTICLE 23', 'Taxes Payable'],
            ['20003602', 'Balance Sheet', 'WITHOLDING TAX PAYABLE ARTICLE 29 YEAR', 'Prepaid Taxes'],
            ['20003700', 'Balance Sheet', 'ACCOUNT PAYABLE-VALUE ADDED TAX OUT', 'Taxes Payable'],
            ['20003800', 'Balance Sheet', 'TAX PAYABLE ARTICLE (4)2', 'Taxes Payable'],
            ['20017200', 'Balance Sheet', 'ACCOUNT PAYABLE TRADE DOMESTIC', 'AP Trade Third Parties'],
            ['20019000', 'Balance Sheet', 'ACCOUNT PAYABLE-GMF', 'AP Trade Related Parties'],
            ['20046076', 'Balance Sheet', 'ACR. EXPENSE OTHER', 'Accrued Expenses'],
            ['20046156', 'Balance Sheet', 'ACR. EXPENSE BASE SALARY', 'Accrued Expenses'],
            ['20090010', 'Balance Sheet', 'COMMON STOCK-GMF', 'Capital Stock'],
            ['20090012', 'Balance Sheet', 'COMMON STOCK-KOPKAR GMF', 'Capital Stock'],
            ['21049000', 'Balance Sheet', 'ACR. EXPENSE GMF', 'Accrued Expenses Related Parties'],
            ['30004100', 'Profit & Loss', 'REVENUE -GARUDA-HODI', 'Revenue from GA Group'],
            ['30004101', 'Profit & Loss', 'REVENUE -GARUDA-HOGF', 'Revenue from GA Group'],
            ['30015011', 'Profit & Loss', 'REVENUE TMB THIRD PARTY', 'Revenue from Third Parties'],
            ['31000060', 'Profit & Loss', 'REVENUE FROM - GA BKS0', 'Revenue from GA Group'],
            ['31000062', 'Profit & Loss', 'REVENUE FROM - GA BTH0', 'Revenue from GA Group'],
            ['31000064', 'Profit & Loss', 'REVENUE FROM - GA BTJ0', 'Revenue from GA Group'],
            ['31000066', 'Profit & Loss', 'REVENUE FROM - GA DJB0', 'Revenue from GA Group'],
            ['31000074', 'Profit & Loss', 'REVENUE FROM - GA KNO0', 'Revenue from GA Group'],
            ['31000078', 'Profit & Loss', 'REVENUE FROM - GA PDG0', 'Revenue from GA Group'],
            ['31000080', 'Profit & Loss', 'REVENUE FROM - GA PGK0', 'Revenue from GA Group'],
            ['31000082', 'Profit & Loss', 'REVENUE FROM - GA PKU0', 'Revenue from GA Group'],
            ['31000084', 'Profit & Loss', 'REVENUE FROM - GA PLM0', 'Revenue from GA Group'],
            ['31000088', 'Profit & Loss', 'REVENUE FROM - GA TKG0', 'Revenue from GA Group'],
            ['31000090', 'Profit & Loss', 'REVENUE FROM - GA TNJ0', 'Revenue from GA Group'],
            ['31000124', 'Profit & Loss', 'REVENUE FROM - GA CGK0', 'Revenue from GA Group'],
            ['31000188', 'Profit & Loss', 'REVENUE FROM - GA DPS0', 'Revenue from GA Group'],
            ['31000190', 'Profit & Loss', 'REVENUE FROM - GA JOG0', 'Revenue from GA Group'],
            ['31000192', 'Profit & Loss', 'REVENUE FROM - GA KOE0', 'Revenue from GA Group'],
            ['31000194', 'Profit & Loss', 'REVENUE FROM - GA LOP0', 'Revenue from GA Group'],
            ['31000196', 'Profit & Loss', 'REVENUE FROM - GA MLG0', 'Revenue from GA Group'],
            ['31000198', 'Profit & Loss', 'REVENUE FROM - GA SOC0', 'Revenue from GA Group'],
            ['31000200', 'Profit & Loss', 'REVENUE FROM - GA SRG0', 'Revenue from GA Group'],
            ['31000202', 'Profit & Loss', 'REVENUE FROM - GA SUB0', 'Revenue from GA Group'],
            ['31000242', 'Profit & Loss', 'REVENUE FROM - GA AMQ0', 'Revenue from GA Group'],
            ['31000244', 'Profit & Loss', 'REVENUE FROM - GA BDJ0', 'Revenue from GA Group'],
            ['31000248', 'Profit & Loss', 'REVENUE FROM - GA BIK0', 'Revenue from GA Group'],
            ['31000250', 'Profit & Loss', 'REVENUE FROM - GA BPN0', 'Revenue from GA Group'],
            ['31000252', 'Profit & Loss', 'REVENUE FROM - GA DJJ0', 'Revenue from GA Group'],
            ['31000254', 'Profit & Loss', 'REVENUE FROM - GA GTO0', 'Revenue from GA Group'],
            ['31000256', 'Profit & Loss', 'REVENUE FROM - GA KDI0', 'Revenue from GA Group'],
            ['31000260', 'Profit & Loss', 'REVENUE FROM - GA MDC0', 'Revenue from GA Group'],
            ['31000264', 'Profit & Loss', 'REVENUE FROM - GA MKQ0', 'Revenue from GA Group'],
            ['31000270', 'Profit & Loss', 'REVENUE FROM - GA PKY0', 'Revenue from GA Group'],
            ['31000272', 'Profit & Loss', 'REVENUE FROM - GA PLW0', 'Revenue from GA Group'],
            ['31000274', 'Profit & Loss', 'REVENUE FROM - GA PNK0', 'Revenue from GA Group'],
            ['31000276', 'Profit & Loss', 'REVENUE FROM - GA SOQ0', 'Revenue from GA Group'],
            ['31000280', 'Profit & Loss', 'REVENUE FROM - GA TIM0', 'Revenue from GA Group'],
            ['31000284', 'Profit & Loss', 'REVENUE FROM - GA TTE0', 'Revenue from GA Group'],
            ['31000286', 'Profit & Loss', 'REVENUE FROM - GA UPG0', 'Revenue from GA Group'],
            ['31003000', 'Profit & Loss', 'REVENUE FROM - AC00', 'Revenue from GA Group'],
            ['31003002', 'Profit & Loss', 'REVENUE FROM - AC01', 'Revenue from GA Group'],
            ['31005009', 'Profit & Loss', 'REVENUE CITILINK', 'Revenue from GA Group'],
            ['31009000', 'Profit & Loss', 'REVENUE TMB GDPS FROM GMF', 'Revenue from GMF'],
            ['31009501', 'Profit & Loss', 'REVENUE THIRD PARTY-OTHERS', 'Revenue from Third Parties'],
            ['41041000', 'Profit & Loss', 'RENTAL EXPENSE-VEHICLE-PROD', 'Manpower Expenses'],
            ['40044009', 'Profit & Loss', 'MANAGEMENT EXPENSE', 'Operating Expenses'],
            ['41044011', 'Profit & Loss', 'PROFESSIONAL EXPENSE CONSULTANT', 'Operating Expenses'],
            ['40002000', 'Profit & Loss', 'BASE SALARY-GEN&ADMIN', 'Staff Expenses'],
            ['40002002', 'Profit & Loss', 'HONORARIUM-GEN&ADMIN', 'Staff Expenses'],
            ['40002315', 'Profit & Loss', 'G&A HEALTHCARE BENEFIT', 'Staff Expenses'],
            ['40002306', 'Profit & Loss', 'TRAINING BENEFIT EXPENSE-GEN&ADMIN', 'Staff Expenses'],
            ['40002132', 'Profit & Loss', 'COMMUNICATION ALLOWANCE-GEN&ADMIN', 'Staff Expenses'],
            ['40002109', 'Profit & Loss', 'EMPLOYEE TAX ALLOWANCE-GEN&ADMIN', 'Staff Expenses'],
            ['40002400', 'Profit & Loss', 'DUTY TRIP EXPENSE-TRAVEL ALLOWANCE-GEN&', 'Staff Expenses'],
            ['40002403', 'Profit & Loss', 'DUTY TRIP EXP-TRANSPORT ALLW-GEN&ADMIN', 'Staff Expenses'],
            ['40002406', 'Profit & Loss', 'DUTY TRIP EXPENSE-HOTEL ALLOWANCE-GEN&A', 'Staff Expenses'],
            ['40004000', 'Profit & Loss', 'BASE SALARY-MANPE', 'Manpower Expenses'],
            ['40004504', 'Profit & Loss', 'SUBCONTRACTING-SERVICES-MANPE', 'Manpower Expenses'],
            ['40004300', 'Profit & Loss', 'PENSION INSURANCE BENEFITS EXPENSE (JHT', 'Manpower Expenses'],
            ['40004303', 'Profit & Loss', 'PENSION HEALTH CARE BENEFIT EXPENSE (KS', 'Manpower Expenses'],
            ['40004505', 'Profit & Loss', 'PRODUCTION SUPPLIES EXPENSE -MANPE', 'Manpower Expenses'],
            ['40004104', 'Profit & Loss', 'OVERTIME ALLOWANCE-MANPE', 'Manpower Expenses'],
            ['40004506', 'Profit & Loss', 'MAINTENANCE&REPAIR EXPENSE-MANPE', 'Manpower Expenses'],
            ['40043029', 'Profit & Loss', 'AIRPORT PASS EXPENSE-G&A', 'Operating Expenses'],
            ['40004507', 'Profit & Loss', 'MISCELLANEOUS EXPENSE-MANPE', 'Manpower Expenses'],
            ['40004102', 'Profit & Loss', 'MEAL EXPENSE-OTHER-MANPE', 'Manpower Expenses'],
            ['40004317', 'Profit & Loss', 'UNIFORM BENEFIT EXPENSE-MANPE', 'Manpower Expenses'],
            ['40004410', 'Profit & Loss', 'DUTY TRIP EXPENSE-DAILY ALLOWANCE-MANPE', 'Manpower Expenses'],
            ['40004508', 'Profit & Loss', 'DRINK WATER EXPENSE-MANPE', 'Manpower Expenses'],
            ['40004509', 'Profit & Loss', 'LOCAL TELEPHONE EXPENSE-TELKOM-MANPE', 'Manpower Expenses'],
            ['40004403', 'Profit & Loss', 'DUTY TRIP EXPENSE-TRANSPORT ALLOWANCE-M', 'Manpower Expenses'],
            ['40004406', 'Profit & Loss', 'DUTY TRIP EXPENSE-HOTEL ALLOWANCE-MANPE', 'Manpower Expenses'],
            ['40004400', 'Profit & Loss', 'DUTY TRIP EXPENSE-TRAVEL ALLOWANCE-MANP', 'Manpower Expenses'],
            ['40004503', 'Profit & Loss', 'SUPPLIES STAT. & OFFICE/ATK-MANPE', 'Manpower Expenses'],
            ['40041002', 'Profit & Loss', 'RENTAL EXPENSE-BUILDING-PROD', 'Manpower Expenses'],
            ['40030008', 'Profit & Loss', 'DEPRECIATION EXP-FURNITURE-PROD', 'Depreciation, Amortization, and Impairment'],
            ['40030017', 'Profit & Loss', 'DEPRECIATION EXP-TOOLS-PROD', 'Depreciation, Amortization, and Impairment'],
            ['40043027', 'Profit & Loss', 'PARKING&TOLL EXPENSE-G&A', 'Operating Expenses'],
            ['40040001', 'Profit & Loss', 'MAINTENANCE&REPAIR EXPENSE-OFFICE&BUILD', 'Operating Expenses'],
            ['40040005', 'Profit & Loss', 'MAINTENANCE&REPAIR EXPENSE-HARDWARE', 'Operating Expenses'],
            ['40002410', 'Profit & Loss', 'DUTY TRIP EXPENSE-DAILY ALLW-GEN&ADMIN', 'Staff Expenses'],
            ['40000317', 'Profit & Loss', 'UNIFORM BENEFIT EXPENSE-PROD', 'Operating Expenses'],
            ['40044016', 'Profit & Loss', 'CORPORATE SOCIAL RESPONSIBILITY EXPENSE', 'Operating Expenses'],
            ['40043020', 'Profit & Loss', 'DRINK WATER EXPENSE', 'Operating Expenses'],
            ['40044002', 'Profit & Loss', 'TAX-OTHERS', 'Other Operating Expenses'],
            ['40043022', 'Profit & Loss', 'SUPPLIES STAT. & OFFICE SUPPLIES/ATK', 'Operating Expenses'],
            ['40043024', 'Profit & Loss', 'STAMP&POSTAGE EXPENSE', 'Manpower Expenses'],
            ['40044008', 'Profit & Loss', 'MEMBERSHIP EXPENSE', 'Operating Expenses'],
            ['40043000', 'Profit & Loss', 'ELECTRICITY CONSUMPTION', 'Operating Expenses'],
            ['40017009', 'Profit & Loss', 'EXPEDITION EXPENSE', 'Operating Expenses'],
            ['41000004', 'Profit & Loss', 'SHORT TERM INCENTIVE-MANPE', 'Manpower Expenses'],
            ['41000100', 'Profit & Loss', 'SHIFT ALLOWANCE - MANPE', 'Manpower Expenses'],
            ['41000102', 'Profit & Loss', 'OVERTIME ALLOWANCE-MANPE', 'Manpower Expenses'],
            ['41000300', 'Profit & Loss', 'EMPLOYEE BENEFIT EXPENSES-OPERATION-PRO', 'Manpower Expenses'],
            ['41002101', 'Profit & Loss', 'OVERTIME ALLOWANCE-GEN&ADMIN', 'Staff Expenses'],
            ['41002300', 'Profit & Loss', 'PENSION INSURANCE BENEFITS EXPENSE (JHT', 'Staff Expenses'],
            ['41002303', 'Profit & Loss', 'PENSION HEALTH CARE BENEFIT EXPENSE-KSH', 'Staff Expenses'],
            ['40044015', 'Profit & Loss', 'ORGANIZATION CERTIFICATE EXPENSE', 'Operating Expenses'],
            ['40045009', 'Profit & Loss', 'PROMOTIONAL EXPENSE-SALES PROMOTIONS', 'Operating Expenses'],
            ['41030004', 'Profit & Loss', 'DEPRECIATION EXP-BUILDING', 'Depreciation, Amortization, and Impairment'],
            ['41030006', 'Profit & Loss', 'DEPRECIATION EXP-HARDWARE-PROD', 'Depreciation, Amortization, and Impairment'],
            ['41030010', 'Profit & Loss', 'DEPRECIATION EXP-VEHICLE-PROD', 'Depreciation, Amortization, and Impairment'],
            ['41030014', 'Profit & Loss', 'DEPRECIATION EXP-SOFTWARE-PROD', 'Depreciation, Amortization, and Impairment'],
            ['41020000', 'Profit & Loss', 'SUBCONTRACTING-SERVICES-MANPE', 'Operating Expenses'],
            ['41040002', 'Profit & Loss', 'MAINTENANCE&REPAIR EXPENSE-SOFTWARE', 'Manpower Expenses'],
            ['41043000', 'Profit & Loss', 'STAMP&POSTAGE EXPENSE-GDPS', 'Operating Expenses'],
            ['50000309', 'Profit & Loss', 'REALIZED GAIN FR DIFFERENCE EXCHANGE RA', 'Operating Expenses'],
            ['50000002', 'Profit & Loss', 'TAX EXPENSE', 'TAX EXPENSE'],
            ['50000209', 'Profit & Loss', 'INTEREST EXPENSE', 'Finance Charges'],
            ['50000215', 'Profit & Loss', 'INTEREST INCOME CHECKING ACCOUNT', 'Finance Income'],
            ['50000310', 'Profit & Loss', 'REALIZED LOSS FR DIFFERENCE EXCHANGE RA', 'Operating Expenses'],
            ['50000300', 'Profit & Loss', 'BANK CHARGE', 'Finance Charges'],
            ['50000302', 'Profit & Loss', 'TRANSACTION ROUNDING', 'Operating Expenses'],
            ['40040008', 'Profit & Loss', 'MAINTENANCE&REPAIR EXPENSE-SOFTWARE', 'Operating Expenses'],
            ['11015000', 'Balance Sheet', 'ACCOUNT RECEIVABLE-ASY0', 'AR Trade Related Parties'],
            ['11018700', 'Balance Sheet', 'ACCRUED REVENUE-ASY0', 'Accrued Revenue Related Parties'],
            ['11041000', 'Balance Sheet', 'ADVANCE PAYMENT-EMPLOYEE', 'Advance Payment'],
            ['21071000', 'Balance Sheet', 'EBO-SEVERENCE BENEFITS AND GRATUITY', 'Employee Benefits Obligation'],
            ['21071004', 'Balance Sheet', 'OCI - SEVERNC&GRAT - ACTUARIAL GAIN/LOS', 'Other comprehensive income'],
            ['31004000', 'Profit & Loss', 'REVENUE FROM - ASY0', 'Revenue from GA Group'],
            ['20092012', 'Balance Sheet', 'RE-UNAPPROPRIATED (MANUALLY) - GDPS', 'RE Unappropriated'],
            ['21028800', 'Balance Sheet', 'ACCOUNT PAYABLE SALARIES', 'Other Account Payable'],
            ['11002010', 'Balance Sheet', 'BANK BNI GIRO-IDR-2201020195', 'Cash and Cash Equivalents'],
            ['11010500', 'Balance Sheet', 'ALW. BDE - A/R FROM GARUDA', 'AR Trade Related Parties'],
            ['11015500', 'Balance Sheet', 'ALW. BDE - A/R FROM ASYST', 'AR Trade Related Parties'],
            ['11019850', 'Balance Sheet', 'ALW. BDE  - A/R FROM TP-PSAK 71', 'AR Trade Third Parties'],
            ['41044012', 'Profit & Loss', 'ENTERTAINMENT EXPENSE', 'Operating Expenses'],
            ['21011000', 'Balance Sheet', 'ACCOUNT PAYABLE-BNI', 'AP Trade Third Parties'],
            ['21010002', 'Balance Sheet', 'ACCOUNT PAYABLE-HODI', 'AP Trade Related Parties'],
            ['11069000', 'Balance Sheet', 'SECURITY DEPOSIT-BUILDING', 'Security Deposit'],
            ['11002014', 'Balance Sheet', 'BANK BCA GIRO-IDR-8681037942', 'Cash and Cash Equivalents'],
            ['40043003', 'Profit & Loss', 'WATER CONSUMPTION', 'Operating Expenses'],
            ['40044021', 'Profit & Loss', 'TAX-FINAL-RENTAL BUILDING AND SPACE', 'Operating Expenses'],
            ['10054000', 'Balance Sheet', 'PREPAID EXPENSE-OTHER', 'Prepaid Expenses'],
            ['11018288', 'Balance Sheet', 'ACCRUED REVENUE- GA LBJ', 'Accrued Revenue Related Parties'],
            ['21059901', 'Balance Sheet', 'UNEARNED REVENUE-TP', 'Other Account Payable'],
            ['31005025', 'Profit & Loss', 'REVENUE FROM - GA LBJ', 'Revenue from GA Group'],
            ['10002914', 'Balance Sheet', 'PANIN BANK - IDR (2705555596)', 'Cash and Cash Equivalents'],
            ['10058008', 'Balance Sheet', 'TRADE RECEIVABLE PKPU GA - NON CURRENT PORTION', 'AR Trade Related Parties'],
            ['10051000', 'Balance Sheet', 'PREPAID INSURANCE', 'Prepaid Expenses'],
            ['11002020', 'Balance Sheet', 'BANK BNI GIRO-VIRTUAL ACCOUNT-1504687979', 'Cash and Cash Equivalents'],
            ['40044001', 'Profit & Loss', 'TAX-PROPERTY AND LAND', 'Operating Expenses'],
            ['40004109', 'Profit & Loss', 'EMPLOYEE TAX ALLOWANCE-MANPE', 'Manpower Expenses'],
            ['40004306', 'Profit & Loss', 'TRAINING BENEFIT EXPENSE-MANPE', 'Manpower Expenses'],
            ['40016002', 'Profit & Loss', 'Fuel Expense-Non Aircraft', 'Operating Expenses'],
            ['40045015', 'Profit & Loss', 'PROMOTIONAL EXPENSE-SPONSORSHIP', 'Operating Expenses'],
            ['40041020', 'Profit & Loss', 'RENTAL EXPENSE-OFFICE EQUIPMENT-PROD', 'Operating Expenses'],
            ['10003318', 'Balance Sheet', 'MANDIRI-GDPS-IDR (1550013073112)', 'Cash and Cash Equivalents'],
            ['40043026', 'Profit & Loss', 'SUBSCRIPTION EXPENSE', 'Operating Expenses'],
            ['40001114', 'Profit & Loss', 'FACILITY ALLOWANCE-OVERHEAD', 'Staff Expenses'],
            ['40043010', 'Profit & Loss', 'LOCAL TELEPHONE EXPENSE', 'Operating Expenses'],
            ['40002129', 'Profit & Loss', 'MEETING AND CONFERENCE EXPENSE-GEN&ADMIN', 'Staff Expenses'],
            ['40003129', 'Profit & Loss', 'MEETING AND CONFERENCE EXPENSE-MARKETING', 'Staff Expenses'],
            ['41002104', 'Profit & Loss', 'PRODUCTION SUPPLIES EXPENSE -GEN&ADMIN', 'Operating Expenses'],
            ['40004510', 'Profit & Loss', 'AIRPORT PASS EXPENSE-MANPE', 'Manpower Expenses'],
            ['41002105', 'Profit & Loss', 'MISCELLANEOUS EXPENSE-GEN&ADMIN', 'Operating Expenses'],
            ['40004511', 'Profit & Loss', 'MEETING AND CONFERENCE EXPENSE-MANPE', 'Manpower Expenses'],
            ['40004512', 'Profit & Loss', 'FUEL EXPENSE-NON AIRCRAFT-MANPE', 'Manpower Expenses'],
            ['40004513', 'Profit & Loss', 'EXPEDITION EXPENSE-MANPE', 'Manpower Expenses'],
            ['40004514', 'Profit & Loss', 'PARKING&TOLL EXPENSE-MANPE', 'Manpower Expenses'],
            ['40004515', 'Profit & Loss', 'OTHER EXPENSES - MANPE', 'Manpower Expenses'],
            ['20050900', 'Balance Sheet', 'PROVISION FOR DOUBTFUL PROGRESS BILLING-GARUDA', 'Accrued Revenue Related Parties'],
            ['20057900', 'Balance Sheet', 'PROVISION FOR DOUBTFUL PROGRESS BILLING-TP-INT', 'Accrued Revenue Third Parties'],
            ['10002256', 'Balance Sheet', 'BTN-GDPS-IDR (24101300017527)', 'Cash and Cash Equivalents'],
            ['41041002', 'Profit & Loss', 'RENTAL EXPENSE-SOFTWARE-GMF0', 'Operating Expenses'],
            ['30006006', 'Profit & Loss', 'REVENUE TMB ADS0', 'Revenue from GA Group'],
            ['40041427', 'Profit & Loss', 'RENTAL EXPENSE-VEHICLE-GEN&ADMIN', 'Operating Expenses'],
            ['10058010', 'Balance Sheet', 'TRADE RECEIVABLE PKPU AC01 - NON CURRENT PORTION', 'AR Trade Related Parties'],
            ['20000070', 'Balance Sheet', 'CURRENT LEASE LIABILITY - VEHICLE TP', 'Current Lease Liability'],
            ['20000076', 'Balance Sheet', 'CURRENT LEASE LIABILITY BUILDING AR00', 'Current Lease Liability'],
            ['20010297', 'Balance Sheet', 'NON CURRENT LEASE LIABILITY BUILDING AR00', 'Non Current Lease Liability'],
            ['90006017', 'Balance Sheet', 'ROU - BUILDING', 'Right Of Use Asset'],
            ['90006016', 'Balance Sheet', 'ROU - ACCUM. DEPR. BUILDING ', 'Right Of Use Asset'],
            ['90006024', 'Balance Sheet', 'VEHICLE - RIGHT OF USE', 'Right Of Use Asset'],
            ['90006025', 'Balance Sheet', 'VEHICLE - RIGHT OF USE (ACC.DEP)', 'Right Of Use Asset'],
            ['20010289', 'Balance Sheet', 'NON CURRENT LEASE LIABILITY - VEHICLE TP', 'Non Current Lease Liability'],
            ['40000323', 'Profit & Loss', 'SEVERANCE&GRATUITY-INTEREST-PROD', 'Manpower Expenses'],
            ['90006028', 'Balance Sheet', 'Building - Right of use - AR00', 'Right Of Use Asset'],
            ['90006029', 'Balance Sheet', 'Building - Right of use - AWS', 'Right Of Use Asset'],
            ['90006031', 'Balance Sheet', 'Building - Right of use (Acc Dep) - AWS', 'Right Of Use Asset'],
            ['20071004', 'Balance Sheet', 'EBO-SEVERENCE BENEFITS AND GRATUITY-C', 'Employee Benefits Obligation'],
            ['40043031', 'Profit & Loss', 'WATER CONSUMPTION-MANPE', 'Manpower Expenses'],
            ['40000122', 'Profit & Loss', 'ELECTRICITY OUTS FAC ALLOWANCE-PROD', 'Manpower Expenses'],
            ['20020297', 'Balance Sheet', 'NON TRADE ACCOUNT PAYABLE DIVIDEN - TP', 'Dividend'],
            ['10005104', 'Balance Sheet', 'TIME DEPOSIT <=3MNTH-KB IND BANK-IDR', 'Cash and Cash Equivalents'],
            ['10058012', 'Balance Sheet', 'TRADE RECEIVABLE PKPU ASY0 - NON CURRENT PORTION', 'AR Trade Related Parties'],
            ['42000229', 'Profit & Loss', 'OTHER EXPENSES', 'Other Operating Expenses'],
        ];

        // Sort group mapping by code (value)
        asort($groupMapping);

        // Process Groups first
        foreach ($groupMapping as $name => $code) {
            $rootCode = substr($code, 0, 1);
            $type = in_array($rootCode, ['1', '2', '9']) ? 'Balance Sheet' : 'Profit & Loss';

            $this->cache["group:{$name}"] = ChartOfAccount::updateOrCreate([
                'code' => $code,
            ], [
                'name' => $name,
                'account_type' => $type,
                'parent_id' => null,
                'is_active' => true,
            ]);
        }

        // Process GL Accounts
        foreach ($data as $row) {
            [$code, $typeFlag, $name, $groupName] = $row;
            $type = $typeFlag;

            $parentId = null;
            if (isset($this->cache["group:{$groupName}"])) {
                $parentId = $this->cache["group:{$groupName}"]->id;
            }

            ChartOfAccount::updateOrCreate([
                'code' => $code,
            ], [
                'name' => $name,
                'account_type' => $type,
                'parent_id' => $parentId,
                'is_active' => true,
            ]);
        }
    }
}
